### ISSUE TITLE
可以考虑无桌面图标

### ISSUE THREAD

**Issue by antinomypa** [Trumeet/MiPushFramework#1]
如果单纯作为一个推送服务的话，桌面图标应该没有必要吧。入口的话，可以使用无障碍服务作为入口，还能达到后台保活的目的（心疼作者，过来提个issue）

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Google Pixel 发送_

**Comment by Trumeet** [comment]
以后会加入设置。见 TODO
