### ISSUE TITLE
1d156a4-SNAPSHOT在Flyme系统上出现的问题

### ISSUE THREAD

**Issue by wordlesswind** [Trumeet/MiPushFramework#104]
![s80423-000539](https://user-images.githubusercontent.com/9050713/39097115-72c0a67a-468a-11e8-91fd-f79d4ed15404.jpg)
打开Manager之后一直弹这个错误，后来去到“手机管家”里查看Manager的权限发现"Manage push service"为“询问”，但程序疑似未发起权限请求，手动赋予权限后问题解决。

**Comment by wordlesswind** [comment]
Service的权限我先赋予了所以没有出现问题，理应是一样的。

**Comment by TimothyZhang023** [comment]
重新安装push app，记得不要清空数据，直接覆盖，或者你直接升级到最新版
