### ISSUE TITLE
register push正常，无推送消息，黑域，lineageos14.1

### ISSUE THREAD

**Issue by yueyingjuesha** [Trumeet/MiPushFramework#110]
小米4 刷的lineageos 14.1的系统，用的magisk安装了mipushfake. 
用户安装的应用全部都用黑域黑掉了，现在就是完全没有通知推送，查看推送记录列表全部应用都是“register push”

 ps.安装的是releases页面 breaking change之前的manager.apk和xmsf_service.apk
，之后的安了打开manager会闪退

**Comment by TimothyZhang023** [comment]
是不是清空过push数据?

**Comment by TimothyZhang023** [comment]
之前版本不提供技术支持了。

如果所有记录中之后 regist push没有发送注册结果说明你可能清空过push数据或者卸载过，这个时候需要重新安装所有支持mipush的app

安装时候先安装最新版push，在安装manager 。 
如果闪退建议提供异常信息。
