### ISSUE TITLE
点击推送消息只是打开那个应用？

### ISSUE THREAD

**Issue by fenying2046** [Trumeet/MiPushFramework#113]
一加3t，氢8.0。点击推送消息不会跳转到那条消息页面，而是只打开那个应用，请问这会是啥原因？

**Comment by TimothyZhang023** [comment]
具体看应用。。

我们这里拉起应用后回去startService ，确实不能保证所有应用都能正确跳转，常见的几种不能跳转
* coolapk 只会弹出消息。
* 微博极速版，跳转地方不对。
* 什么值得买，新的activity在最底下

如果所有应用都不跳转，检查一下辅助功能或者使用情况是不是给了权限
最新版可以切换两种检测前台模式，可以换一种试试
