### ISSUE TITLE
[小建议] 请问能否提供下README里面显示的PushDemo

### ISSUE THREAD

**Issue by eitanlevy97** [Trumeet/MiPushFramework#118]
这样用户就可以自己测试xiaomi推送框架了，防止一些不是bug的bug提交上来～

另外在Oreo上，淘宝死活不认xiaomi。。

**Comment by TimothyZhang023** [comment]
这个是小米PushSDK的demo自己可以去官方工具


对于淘宝死活不认xiaomi
这个用应用变量模拟 xiaomi mix就行
