### ISSUE TITLE
安卓8.1无法使用

### ISSUE THREAD

**Issue by Linlin1314** [Trumeet/MiPushFramework#120]
努比亚 安卓8.1
设置好后主界面空白，下方一直弹出
 We need top.trumeet.mipush.permissions.WRITE_SETTINGS to work

**Comment by TimothyZhang023** [comment]
试试先安装 push 再安装manager ？

**Comment by Linlin1314** [comment]
我是先装的push再装的manager，因为先装manager再装push在向导的第二个界面点下一步会直接回到第一步。

**Comment by TimothyZhang023** [comment]
试一下最新测试版。。

**Comment by zhou1012** [comment]
使用最新的af16bab-SNAPSHOT问题依旧

**Comment by 873578156** [comment]
同样问题在努比亚Z17miniS上，安卓7.11，似乎是没有写入设置的权限，老大你能否更改下app的源码，使其在第一次启动把所有权限申请到位。
