### ISSUE TITLE
魔趣8.1无法通知栏收到推送

### ISSUE THREAD

**Issue by LKX787832305** [Trumeet/MiPushFramework#123]
有xposed和masigk，但没有黑域和绿色守护，没有电池优化，应用权限全部给了，后台自启都开了。小米note2魔趣Rom8.1，问题是应用里头看到了推送记录，但通知栏从来没显示过。另外那些支持小米推送的APP的XMPush我也全用写轮眼关了，只有“小米推送服务”这个应用的XMPush保留着。求大佬解决

**Comment by LKX787832305** [comment]
[file.log](https://github.com/Trumeet/MiPushFramework/files/2024515/file.log)

**Comment by LKX787832305** [comment]
14分钟前，知乎推送了消息，IOS和MIPush都推了，但是在小米Note2的8.1魔趣上无法在通知栏接收到
![img_0817](https://user-images.githubusercontent.com/39504701/40340498-c106c24a-5db1-11e8-9849-5f290a385ab9.png)
![screenshot_ _20180522-111518](https://user-images.githubusercontent.com/39504701/40340511-d04c6ea8-5db1-11e8-835e-8aff6d9b1af8.png)

**Comment by TimothyZhang023** [comment]
> 另外那些支持小米推送的APP的XMPush我也全用写轮眼关了，只有“小米推送服务”这个应用的XMPush保留着。

请不要这样做，推送信息处理需要依赖messageHandler

**Comment by TimothyZhang023** [comment]
如果你觉得是标题栏没有通知，这个要检查rom的通知权限。
看你这个记录，应该是没有推送过来，收到推送不等于有内容的推送是不是会显示的

**Comment by LKX787832305** [comment]
谢谢大佬解答，目前已经解决了部分问题。现在还面临一个问题一个疑惑。当我安装新的支持MiPush的应用后，我用写轮眼查看了服务的禁止情况发现，有的XMPush会被自动禁止，而有的就不会，这是为什么？譬如今日头条就是这样的。按照您的提示，我没有用写轮眼手动禁止今日头条的XMPush，但是今日头条一直没有收到过小米推送服务的推送

**Comment by LKX787832305** [comment]
谢谢大佬解答，目前已经解决了部分问题。现在还面临一个问题一个疑惑。当我安装新的支持MiPush的应用后，我用写轮眼查看了服务的禁止情况发现，有的XMPush会被自动禁止，而有的就不会，这是为什么？譬如今日头条就是这样的。按照您的提示，我没有用写轮眼手动禁止今日头条的XMPush，但是今日头条一直没有收到过小米推送服务的推送
Duplicate of 4#

**Comment by LKX787832305** [comment]
谢谢大佬解答，目前已经解决了部分问题。现在还面临一个问题一个疑惑。当我安装新的支持MiPush的应用后，我用写轮眼查看了服务的禁止情况发现，有的XMPush会被自动禁止，而有的就不会，这是为什么？譬如今日头条就是这样的。按照您的提示，我没有用写轮眼手动禁止今日头条的XMPush，但是今日头条一直没有收到过小米推送服务的推送 @TimothyZhang023 
还有啊。。。大佬，，，这个玩意怎么回复你的评论，，，我不会啊。。，萌新
