### ISSUE TITLE
如果可以是否可以给push增加一个设备管理员权限，用来保活

### ISSUE THREAD

**Issue by yanyumihuang** [Trumeet/MiPushFramework#124]
如题就跟qpay有点类似，通过pay一样利用这种方式进行保活，但并不要想qpay一样不授予权限就某些功能不能使用，即可。提出这个issue的原因是经常性的push自动停止，除非改变一下网络状态，或者打开有mipush的应用来拉起。，否则就一直那样停止了。毕竟push才是这个应用的根本，但靠设备本身的保活很难。

**Comment by yanyumihuang** [comment]
@Trumeet

**Comment by TimothyZhang023** [comment]
1. 滥用设备管理员不好吧。
2. 很多rom有界面锁定避免清理功能，新版push已经加上了
