### ISSUE TITLE
[af16bab]记录的时间显示问题

### ISSUE THREAD

**Issue by wordlesswind** [Trumeet/MiPushFramework#125]
![screenshot_20180524-174522](https://user-images.githubusercontent.com/9050713/40478003-755499ce-5f7a-11e8-9366-e687ea68391c.jpg)
一直为24小时。

**Comment by wordlesswind** [comment]
![screenshot_20180525-103014](https://user-images.githubusercontent.com/9050713/40523135-d0288f36-6006-11e8-8676-becf5344394a.jpg)
时区错误。

**Comment by TimothyZhang023** [comment]
已知bug， 一直都有

**Comment by TimothyZhang023** [comment]
新版即将修复
