### ISSUE TITLE
老是提示要允许小米推送服务，执行未知操作吗？

### ISSUE THREAD

**Issue by chscsj2001** [Trumeet/MiPushFramework#126]
从4月20几号版本更新后一直提示这个，没法用，系统android 6.0, 机型海信A2
![screenshot_20180524-233647_](https://user-images.githubusercontent.com/39595919/40496414-3f4c504c-5fac-11e8-9c01-a575616e9185.png)

**Comment by TimothyZhang023** [comment]
全部换最新版试试呢

**Comment by chscsj2001** [comment]
都换过了

**Comment by chscsj2001** [comment]
而且换过后，不能推送了，就算推送了也不能跳转到应用，请问需要我提供什么信息给你

**Comment by Minelu** [comment]
![](https://i.imgur.com/xCq19ul.png)
给它权限就好了

**Comment by TimothyZhang023** [comment]
1. 权限
2. 给了权限还是不能跳转的，可以在设置里面修改 前台应用检测模式， 切换为兼容模式

**Comment by chscsj2001** [comment]
权限是哪个权限，android6.0的，我都完全信任了

**Comment by chscsj2001** [comment]
可以在设置里面修改 前台应用检测模式， 切换为兼容模式？这个之前有切换过，还是一样

**Comment by TimothyZhang023** [comment]
push更新了么？

**Comment by chscsj2001** [comment]
还没更新，有修复这个问题吗，我现在退到4月的版本，要不没法用

**Comment by TimothyZhang023** [comment]
请确认push和manager全部更新到最新版本。


如果安装两遍依然不行的话，可能是rom问题。

**Comment by chscsj2001** [comment]
五月底有更新了最新了，两个都更新了，还是一样，后续有对这个问题进行修复吗，如果有修复了这个问题，我再更新试试

**Comment by TimothyZhang023** [comment]
可以更新最新版试试
