### ISSUE TITLE
[教程] 诺基亚安卓用户看这里

### ISSUE THREAD

**Issue by Hill-98** [Trumeet/MiPushFramework#131]
首先确保你的诺基亚安卓手机已解锁 BootLoader 或 已获取 Root 权限。

教程地址：[https://www.mivm.cn/nokia-android-mipush/](https://www.mivm.cn/nokia-android-mipush/)

完美解决 MiPush 服务无法在后台常驻。

**Comment by TimothyZhang023** [comment]
@Trumeet  打开一下wiki 功能吧，把教程类收进去

**Comment by TimothyZhang023** [comment]
收录在https://github.com/Trumeet/MiPushFramework/wiki/%5B%E6%95%99%E7%A8%8B%5D-%E8%AF%BA%E5%9F%BA%E4%BA%9A%E7%AF%87
