### ISSUE TITLE
点击消息无法正常跳转到推送的内容

### ISSUE THREAD

**Issue by zl939144892** [Trumeet/MiPushFramework#137]
点击消息后, 能正常打开APP, 但是不会跳转到推送的内容页面.
比如一个新闻APP, 推送了一个新闻, 我点击之后只会打开APP, 不会继续跳转到推送的那条新闻.
不清楚是BUG还是暂时未开发此功能

**Comment by TimothyZhang023** [comment]
这个比较困难，我们还在提高跳转成功率。
目前方案下短时间内很难有突破。



close due to dup to #78

**Comment by zl939144892** [comment]
嗯嗯, 加油
