### ISSUE TITLE
知乎没法正常进冰箱了

### ISSUE THREAD

**Issue by wangzhao2222** [Trumeet/MiPushFramework#139]
成功跟mi push挂钩以后，绿色守护没法正常判断知乎的状态了
![screenshot_20180611-084055](https://user-images.githubusercontent.com/36464256/41214837-f00b15b8-6d7f-11e8-838d-0ba6ca2e8537.png)

**Comment by TimothyZhang023** [comment]
绿守问题不了解， @oasisfeng 能帮忙解答一下么？

不太清由于识别成小米之后，应用有什么变化，我也经常遇到程序被识别为工作中，我也不能确定是应用问题还是识别成小米之后的问题。。

目前xposed插件没有白名单功能，你可以关闭插件使用应用变量。@wangzhao2222

**Comment by wangzhao2222** [comment]
@TimothyZhang023 并没有使用xposed....

**Comment by oasisfeng** [comment]
我也不能确定具体的原因…… 不过最近我也正在调查这类比较奇怪的被 Android 系统报告为『工作中』的状态，暂时还没有头绪。
