### ISSUE TITLE
不能修复无法收到的应用

### ISSUE THREAD

**Issue by dzeongit** [Trumeet/MiPushFramework#14]
[file.txt](https://github.com/Trumeet/MiPushFramework/files/1256995/file.txt)

**Comment by ag2s20150909** [comment]
@Trumeet 

[file.txt](https://github.com/Trumeet/MiPushFramework/files/1257138/file.txt)

**Comment by TimothyZhang023** [comment]
功能bug太多已经下掉了。后面看情况加入。
