### ISSUE TITLE
yota3偶尔可以接收到推送，但无法在状态栏显示

### ISSUE THREAD

**Issue by 962978926** [Trumeet/MiPushFramework#140]
[file.log](https://github.com/Trumeet/MiPushFramework/files/2092784/file.log)
![screenshot_2018-06-11-14-28-23](https://user-images.githubusercontent.com/23065718/41273815-96629828-6e4d-11e8-8423-e82b1eb91108.png)

**Comment by TimothyZhang023** [comment]
java.lang.SecurityException: WifiService: Neither user 10176 nor current process has android.permission.ACCESS_WIFI_STATE.
这个权限最好给一下

日志没看到异常， 确认一下push服务没有重启过，如果最新版的话，开启一下后台锁定之类的

**Comment by 962978926** [comment]
感谢！今天终于推了😂
