### ISSUE TITLE
如图，努比亚Z17miniS，3.04版本，从提示看，似乎是缺少权限。

### ISSUE THREAD

**Issue by 873578156** [Trumeet/MiPushFramework#144]
![screenshot_2018-06-21-13-50-04](https://user-images.githubusercontent.com/20461982/41700827-952fb0d8-755c-11e8-8911-8daff4aad991.png)
![screenshot_2018-06-21-13-50-17](https://user-images.githubusercontent.com/20461982/41700828-959bd772-755c-11e8-90aa-2837e69e56ce.png)

**Comment by 873578156** [comment]
尝试了好多次，不行

**Comment by funcc** [comment]
@873578156  设置，应用程序，小米推送服务，1项其它权限，其他权限，打开“Manage push service”

**Comment by 873578156** [comment]
那么，是不是说，在努比亚的ui上是无法注册这个权限的

**Comment by 873578156** [comment]
因为我在appoptx里也看不到这个权限

**Comment by TimothyZhang023** [comment]
不能确定是不是 nubia的rom有权限限制之类的。

**Comment by 873578156** [comment]
请求解决方案

**Comment by TimothyZhang023** [comment]
安装最新版试试，不清楚nubia rom有什么限制。

**Comment by 100369548** [comment]
vivo nex的Manage push service也打不开，点开启返回后会自动关闭

**Comment by TimothyZhang023** [comment]
@100369548  nex版本是8.1还是P？。。。你们都这么有钱么。。。

**Comment by 100369548** [comment]
@TimothyZhang023 安卓8.1

**Comment by zhou1012** [comment]
自己用adb手动注册权限也注册不上，nubia ui又限制了什么东西

**Comment by TimothyZhang023** [comment]
更换最新版呢？

**Comment by TimothyZhang023** [comment]
新版已经增强兼容性

**Comment by zhou1012** [comment]
已经解决，感谢
