### ISSUE TITLE
如何在miui系统上使用mipushframework（how to use mipushframework on miui device）

### ISSUE THREAD

**Issue by mgsqz** [Trumeet/MiPushFramework#145]
remove /system/app/xiaomiframework
install xmsf_service.apk into system/app/xiaomiframework
install manager.apk normally,
ok! enjoy it!

**Comment by TimothyZhang023** [comment]
are u sure that   remove /system/app/xiaomiframework  is safe ?

offical miui rom contains mipush service default

**Comment by mgsqz** [comment]
in most global rom，it‘s ok.
