### ISSUE TITLE
ad46c48-SNAPSHOT manager 无法安装

### ISSUE THREAD

**Issue by Indexyz** [Trumeet/MiPushFramework#149]
[![Screenshot_Package_installer_20180627-012119.png](https://i.loli.net/2018/06/27/5b32762e42f26.png)](https://i.loli.net/2018/06/27/5b32762e42f26.png)

环境：
Android 8.1
小米5

上一个 Release 可以安装

**Comment by TimothyZhang023** [comment]
是升级么？

**Comment by TimothyZhang023** [comment]
能截图一下你之前安装的版本的详细信息么？应用那个详细信息

**Comment by Indexyz** [comment]
@TimothyZhang023 全新安装

**Comment by TimothyZhang023** [comment]
我这里测试没有问题。。


上一个release指的是哪一个？签名没有换过，确认没有安装其他版本的manager

**Comment by Indexyz** [comment]
@TimothyZhang023 0429112-SNAPSHOT

**Comment by TimothyZhang023** [comment]
我验证了一下，没有区别，换个网络重新下载看看吧

**Comment by TimothyZhang023** [comment]
麻烦提供一下rom信息

**Comment by TimothyZhang023** [comment]
是魔趣么？

**Comment by Indexyz** [comment]
小米 5
AEX.Mod

**Comment by TimothyZhang023** [comment]
rom是原版么？还是国人二次打包的？

如果是二次打包的rom，之前有rom集成mipush框架么？

**Comment by Indexyz** [comment]
https://www.androidfilehost.com/?fid=5862345805528040291
我现在已不再使用此 ROM

**Comment by TimothyZhang023** [comment]
之前无法安装是因为新版不支持platform版本，而你之前安装了platform版本的push，权限签名不一致。。。
