### ISSUE TITLE
无法推送允许的应用的通知

### ISSUE THREAD

**Issue by Certainlies** [Trumeet/MiPushFramework#15]
日志链接：

https://drive.google.com/file/d/0B49sUwbaTVM8T0cxWDJfQkRybG8/view?usp=drivesdk

酷安有新消息时，弹出了允许推送。但是点了允许后，仍然推送不了通知。
系统是Android 7.1.2版本的rr os，型号为一加2。0.3 Test 1
后台有绿色守护，黑域，未对框架绿色化及黑域

**Comment by Certainlies** [comment]
刚刚发现应该是界面没刷新的问题，回到主屏再打开，刷新后就有了允许的应用

**Comment by Trumeet** [comment]
请升级最新版试一下，如果还有推送问题请到 #34 反馈，谢谢
