### ISSUE TITLE
vivo nex手机可以使用。但是推送时只出现在记录里，不会触发系统推送。

### ISSUE THREAD

**Issue by 100369548** [Trumeet/MiPushFramework#154]
系统所有权限都给了，app能注册，但系统收不到推送通知
![screenshot_20180713_102756](https://user-images.githubusercontent.com/12770432/42669610-edbe5af0-8688-11e8-9c32-0e7447a33e62.jpg)
![screenshot_20180713_102813](https://user-images.githubusercontent.com/12770432/42669611-edf4dfee-8688-11e8-968e-569532c40e24.jpg)
![screenshot_20180713_102823](https://user-images.githubusercontent.com/12770432/42669612-ee2da37e-8688-11e8-8114-ca889cf0b819.jpg)

log文件
[file.log](https://github.com/Trumeet/MiPushFramework/files/2191046/file.log)

**Comment by TimothyZhang023** [comment]
把 小米推送服务 manager取消电池优化试试？

**Comment by 100369548** [comment]
感谢开发者，已经可以正常推送了

**Comment by 100369548** [comment]
感谢开发者，已经可以正常推送了
