### ISSUE TITLE
关于push服务异常，请关闭ROM的高级优化功能

### ISSUE THREAD

**Issue by NonXZhu** [Trumeet/MiPushFramework#156]
用的三星系统，看到也有酷友有这个问题。推送基本是正常的，但有时候就会弹出这样的toast。

[log.txt](https://github.com/Trumeet/MiPushFramework/files/2195742/log.txt)

**Comment by TimothyZhang023** [comment]
系统或者优化软件拦截了。

**Comment by NonXZhu** [comment]
优化软件就用了一个绿色守护，但没有对“push”进行限制。三星ROM也全部都放行了，没有找到任何能拦截它的地方啊。

**Comment by CaiMiao** [comment]
同

**Comment by TimothyZhang023** [comment]
@CaiMiao  一加就是关闭电池高级优化

**Comment by NonXZhu** [comment]
话说除了“push”服务，“小米推送服务”这个管理程序需要放行吗。本来不需要干什么的这个管理程序被三星的管理器拦截了24次。

**Comment by NonXZhu** [comment]
@TimothyZhang023 看来我启动后已经没问题了。之后可以在第一次安装的向导处加一个提示，两个程序都需要启用，或者出错的toast多加一个提醒，那这个问题发生几率就很小了。我看着那边的表述有点含糊。

**Comment by TimothyZhang023** [comment]
@NonXZhu  这个后面会优化
