### ISSUE TITLE
装了这个后，原本能推送的全不推送了））））））

### ISSUE THREAD

**Issue by ag2s20150909** [Trumeet/MiPushFramework#16]
手机：vivo y66
Android版本：6.0.1
Fun touch os:PD1621_A_1.11.1

[file.txt](https://github.com/Trumeet/MiPushFramework/files/1257150/file.txt)

**Comment by ag2s20150909** [comment]
@Trumeet

**Comment by Trumeet** [comment]
从现在的状况看像是服务总是停止啊..
有更多日志/推送问题建议在 #34 说一下。
