### ISSUE TITLE
能否考虑移植miui的框架？

### ISSUE THREAD

**Issue by uian2000** [Trumeet/MiPushFramework#167]
第三方rom里无法使用小米的通讯录、短信、通话记录等同步，无法使用小米公交卡。
自己尝试去odex后安装，提示gson.jar共享库丢失，然而小米rom里的只是空壳…

能否考虑移植框架，或者提供下思路？

**Comment by TimothyZhang023** [comment]
很难移植 小米公交卡 这种单独功能，框架牵扯的依赖比较多，要分离干净可能性不大 

具体移植得逆向看这个框架个功能实现。
