### ISSUE TITLE
一加5 Android 8.1 Push/ROM支持 被加密，解锁后才显示通知详情

### ISSUE THREAD

**Issue by CloudnuY** [Trumeet/MiPushFramework#168]
**Describe the bug/**

一加5 氢OS Android8.1 安装主程序和服务之后，“后台服务保活”界面如同 被系统应用锁加密一样（如下图），每次都需要指纹验证或输入密码进入保活Activity。
系统已打开指纹和密码，设置->安全和隐私->应用锁 中已打开“通知内容隐藏（开启了应用锁的应用，不会显示其通知内容）”选项，应用锁列表为空，如下图。

以上导致如下现象：每次锁屏再解锁之后，通知栏只显示图标，不显示通知详情，右边小三角也点不开，只有重新打开一遍保活服务并指纹或密码进入界面后通知栏恢复正常，就好像通知服务和所有走MiPush的应用被加入到了应用锁中一样。

**To Reproduce**
1.  正常安装主程序及服务，将服务排除电池优化，将保活服务在后台列表中加锁；
2.  锁屏，解锁，出现错误
3.  重新打开保活，输入系统密码或指纹，在下次锁屏之前都恢复正常

**Expected behavior**
无，此现象是否正常

**Screenshots**（截图）
![screenshot_20180728-221257](https://user-images.githubusercontent.com/14636247/43357510-67b5905c-92b5-11e8-8586-3a881a2fe911.jpg)

**Logs** （日志）
[file.log](https://github.com/Trumeet/MiPushFramework/files/2238052/file.log)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: H2OS
 - Android Version: 8.1.0
 - Version: 0.3.4.20180727.9688257

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）
此现象打开从系统升级8.0开始，到8.1，root和未root都存在此问题，安装Magisk和伪装小米服务及不安装都存在此问题，前几天才发现「解锁保活服务可以显示详情」这种解决办法，完全和被加入到系统应用锁的现象一模一样

**Comment by TimothyZhang023** [comment]
@Trumeet   这种情况是push被加锁了，但是管理界面看不到因为push没有界面

**Comment by TimothyZhang023** [comment]
@CloudnuY  你说的情况我知道，“ “后台服务保活”界面如同 被系统应用锁加密一样 ” ，就是被锁了，但是没有理论上通知和跳转是没有影响的。

**Comment by TimothyZhang023** [comment]
@CloudnuY  后台服务保活 只要操作一次，然后锁住就行了。

**Comment by TimothyZhang023** [comment]
@CloudnuY  通知内容隐藏 关掉先显示通知吧。。

**Comment by Trumeet** [comment]
@TimothyZhang023 知道为什么会被锁么..

**Comment by TimothyZhang023** [comment]
@Trumeet

**Comment by kongdeli** [comment]
一加5t 氧os有同样的问题。

**Comment by shanefengcn** [comment]
> @Trumeet
> 我这里是经过某次升级之后被锁住了，很迷的操作。
> 我之前用等于4的时候 play服务被锁，更奇妙，触发原因却是看不出来。
> 
> 我这里，自己打了个包，把push设置了一个main activity，然后就可以关闭应用锁了，是这样luancher里面会有push的图标这个很恶心。
> 
> 对了目前对于push有默认activity需求的情况有
> 
> 1. 一加的应用锁
> 2. 小米运动app的通知到手环功能
> 3. 锤子rom的疑似不弹出通知问题
> 
> 我想能不能打一个push带默认activity的分支版本 (就像之前platform那样)

先装一个带activity版本的push 关闭应用锁 再覆盖升级不带activity版本的push 应用锁还在吗？

**Comment by shanefengcn** [comment]
@TimothyZhang023

**Comment by TimothyZhang023** [comment]
> > @Trumeet
> > 我这里是经过某次升级之后被锁住了，很迷的操作。
> > 我之前用等于4的时候 play服务被锁，更奇妙，触发原因却是看不出来。
> > 我这里，自己打了个包，把push设置了一个main activity，然后就可以关闭应用锁了，是这样luancher里面会有push的图标这个很恶心。
> > 对了目前对于push有默认activity需求的情况有
> > 
> > 1. 一加的应用锁
> > 2. 小米运动app的通知到手环功能
> > 3. 锤子rom的疑似不弹出通知问题
> > 
> > 我想能不能打一个push带默认activity的分支版本 (就像之前platform那样)
> 
> 先装一个带activity版本的push 关闭应用锁 再覆盖升级不带activity版本的push 应用锁还在吗？

可以解决

**Comment by ZhongJinMing** [comment]
我也遇到了同样的问题，所以能不能告诉我怎么make一个activity的push

**Comment by shanefengcn** [comment]
这个需要等开发者发出来……

________________________________
发件人： ZhongJinMing <notifications@github.com>
发送时间： 2018年10月8日星期一 15:44
收件人： Trumeet/MiPushFramework
抄送： Shane; Comment
主题： Re: [Trumeet/MiPushFramework] 一加5 Android 8.1 Push/ROM支持 被加密，解锁后才显示通知详情 (#168)


我也遇到了同样的问题，所以能不能告诉我怎么make一个activity的push

―

**Comment by shanefengcn** [comment]
等开发者吧……

**Comment by TimothyZhang023** [comment]
召唤 @Trumeet

**Comment by Trumeet** [comment]
我暂时真的不能同意这个请求，因为我个人不太喜欢这样做。现在能否想出不需要修改代码的解决方案？

我会在分析 H2OS 后给出详细说明。（咕姑姑

**Comment by ZhongJinMing** [comment]
我现在的解决方案是：一加在应用锁有一个开关——“通知内容隐藏”，我只有关了这个开关才能看到推送的消息，但是这样一来所有加锁应用的推送都会在通知栏显示详情了，起不到保护隐私的作用。所以现在问题的关键是：这个没有图形界面的程序被一加上了应用锁，导致无法取消，因为应用锁列表里根本看不到这个应用。希望对你有帮助

**Comment by Trumeet** [comment]
@ZhongJinMing 好的，谢谢（

**Comment by Trumeet** [comment]
@CloudnuY @TimothyZhang023 @ZhongJinMing 
打扰了。请问一下，是所有无图标 App 都会被自动加锁吗？

**Comment by TimothyZhang023** [comment]
> @CloudnuY @TimothyZhang023 @ZhongJinMing
> 打扰了。请问一下，是所有无图标 App 都会被自动加锁吗？

不清楚触发条件。并不是必现。关闭之后不会被重新加锁

**Comment by TimothyZhang023** [comment]
> @ZhongJinMing 请问您所说的这些 APP 是系统应用吗？

不是。

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 好奇怪呀（

而且是在某次升级时候触发的，后面就不会再出现了。

**Comment by TimothyZhang023** [comment]
fixed with 0.3.6
