### ISSUE TITLE
HTC10 RR ROM, Android7.1.2，显示注册推送、收到推送成功，但是没有浮动通知

### ISSUE THREAD

**Issue by lovelyelfpop** [Trumeet/MiPushFramework#17]
浮动通知功能已经开启。
电池未优化，没有绿色它
记录上显示的 都是各种成功，但是没有通知弹出来

**Comment by doudoumiao** [comment]
一样的情况

**Comment by Certainlies** [comment]
注意提供日志和系统及型号...

**Comment by rightmans** [comment]
@Certainlies 写在标题里了

**Comment by lovelyelfpop** [comment]
@Certainlies 获取日志提示文件为空。系统和型号，标题写了

**Comment by yEs1do** [comment]
米5 RR 7.1.1，状况完全相同

**Comment by TimothyZhang023** [comment]
可以测试一下最新版

**Comment by TimothyZhang023** [comment]
fixed at https://github.com/Trumeet/MiPushFramework/releases/tag/0429112-SNAPSHOT
