### ISSUE TITLE
“ROM 支持”页面文字BUG

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#170]
![](https://i.imgur.com/Plv8eoF.png)
如图。
本人的ROM是Aokp，Android 8.1。

**Comment by TimothyZhang023** [comment]
这个问题知道的。

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 请问一下为何一直不修复此问题？

**Comment by Trumeet** [comment]
疏忽了.... 不过还是建议不要在没解决的时候关闭，因为我们一般只关注 Open 的 issue 们。

**Comment by Trumeet** [comment]
抱歉，刚刚提交 https://github.com/Trumeet/MiPushFramework/commit/e65fd1f3dda1c44c5eec78ae8838357a2f6e7f33 修复了，忘了加 `close #170`，所以手动关闭。
