### ISSUE TITLE
三星S9+注册异常

### ISSUE THREAD

**Issue by carlmemory** [Trumeet/MiPushFramework#171]
国行系统，magisk的fake framework装了，push给了自启动和无视电池优化权限，打开的软件也都给了自启和无视电池优化的权限，刷机来回弄了三次了，就是注册不上………所有软件都显示注册异常

**Comment by carlmemory** [comment]
![screenshot_20180806-071206_](https://user-images.githubusercontent.com/39611217/43721603-13227548-9948-11e8-94e2-2e3dc16998a6.jpg)

**Comment by carlmemory** [comment]
![screenshot_20180806-071327_html viewer](https://user-images.githubusercontent.com/39611217/43721654-411654b0-9948-11e8-8338-c77d58c00b19.jpg)
log文件都是一样的，都是第一行显示push is not.connected。人在国外，试过vpn，也不行，跪求大佬们帮忙

**Comment by mailliangzi** [comment]
我s8 安装后也是注册异常 但是卸载注册异常app后 重启手机并且重新安装注册异常的app  mipush提示 正常了，但是还是收不到推送

**Comment by TimothyZhang023** [comment]
安装今天最新的测试版本试一下

**Comment by carlmemory** [comment]
谢谢大佬，马上试

**Comment by TimothyZhang023** [comment]
close due to inactive
