### ISSUE TITLE
功能建议：在Manager显示未注册推送的应用

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#174]
此举有利于普通用户首次使用推送框架时有针对性地对使用小米推送的应用作出一些操作[如打开应用或卸载重装使其注册推送]。亦能消除用户在首次打开Manager看到“应用”页一片空白而产生设备中没有应用使用小米推送或其他误会。

**Comment by Lelouch-000** [comment]
嗯，我也觉得这样比较好，可以将支持米推的都显示在列表里，这样也能快点代开相应app来注册，不用一个个app都打开，而且还不知道它支不支持

**Comment by Trumeet** [comment]
将会开发这一功能。
