### ISSUE TITLE
被禁用的App在推送消息时不显示图标

### ISSUE THREAD

**Issue by draplater** [Trumeet/MiPushFramework#177]
现在即使App被禁用也能收到消息，这很好；但是显示消息时不显示App的名称和图标。

这个问题可以这么解决：在应用注册推送时将App的名称和图标缓存下来，收到消息时若发现应用不存在，则使用缓存的名称和图标。

**Comment by TimothyZhang023** [comment]
> 现在即使App被禁用也能收到消息，这很好；但是显示消息时不显示App的名称和图标。

这个应该是你rom问题。提供一下rom信息吧

**Comment by Trumeet** [comment]
看了一下，底层获取 Icon 是 `getApplicationIcon`，内部使用 `getApplicationInfo`，不涉及是否 Disabled。所以说可能是 ROM 问题咯（

**Comment by TimothyZhang023** [comment]
建议更换rom解决

**Comment by Trumeet** [comment]
@TimothyZhang023 这个问题暂时还不太敢确定是 ROM 的问题，不过大体上能排除是项目的问题。
不过楼主 @draplater 到现在也没有回复是什么 ROM，我也很无奈啊..
