### ISSUE TITLE
[Help Wanted] 所有应用都注册异常

### ISSUE THREAD

**Issue by tnqzh123** [Trumeet/MiPushFramework#178]
如题所述，所有应用都注册异常。
已按照 Manager 内提供的帮助文档进行自查，之前并未卸载过 Push，也未清空过数据（不如说我刷入 ROM 之后的第一件事就是安装 Push 和 Manager）。已卸载并重新安装过提示注册异常的应用，仍然注册异常。但“事件”页面内都是“Register Push 成功”。
机型是红米 4 高配版，ROM 是 Havoc 20180823，Android 版本为 8.1.0。已启用 Magisk 模块。Push 和 Manager 都是 releases 里最新的（0.3.4.20180816.16e1bf1）。
log 如下：
[file.log](https://github.com/Trumeet/MiPushFramework/files/2375913/file.2.log)

**Comment by TimothyZhang023** [comment]
说明注册回调被拦截了。。可以检查一下是不是有什么优化软件或者开关。

部分rom限制了应用间广播，目前已知的是DK rom。
如果解决不了建议找romer作者解决这个问题。
