### ISSUE TITLE
MipushFake 刷入失败

### ISSUE THREAD

**Issue by fantuyuan** [Trumeet/MiPushFramework#179]
在magisk manager里直接刷和进recovery都不行。
magisk manager版本17.1
一加3 Android 8.0

**Comment by Trumeet** [comment]
1. 请提供日志或截图
2. 这得 @cubesky （逃跑

**Comment by fantuyuan** [comment]
- Copying zip to temp directory
- Installing MiPushFake.zip
***********************************
! /data/magisk isn't setup properly!
! Please install Magisk v13.1+!
***********************************
! Installation failed

**Comment by cubesky** [comment]
请使用 Magisk App 中的下载再试一次

**Comment by fantuyuan** [comment]
已解决。ths

名称为：XiaoMi Push Framework Fake
