### ISSUE TITLE
自动注册新应用时显示短暂提示

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#180]
“自动注册应用”开启的情况下，应用的新增太隐蔽了。
应该默认或允许在首次注册时显示消息（`Toast.makeText`）。

**Comment by Trumeet** [comment]
ok，感谢

**Comment by yfdyh000** [comment]
有点担心`permission_notification_on_register`的实现方式与我设想的不同。我想的是一个全局开关——自动注册应用 下方，而非各个应用的选项（那样想关太麻烦），以及非每次注册都显示（那样没什么意义，软件可能经常注册推送）。

**Comment by Trumeet** [comment]
@yfdyh000 单个应用默认是开的（

**Comment by yfdyh000** [comment]
@Trumeet 补充和纠正：如果是应用级的选项，我想不到怎么提前、预先关闭该注册提示，有些用户可能喜欢静默注册，即当前的效果。

**Comment by Trumeet** [comment]
@yfdyh000 那添加全局选项？

**Comment by Trumeet** [comment]
@yfdyh000 好的，请新建 Issue 来提交 `增添全局选项  balabala`，以便我们区分问题，谢谢。
