### ISSUE TITLE
提供“清除数据”解决注册异常的替代方案（删除mipush xml）

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#182]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
支持MiPush的应用启动后不注册推送或者注册异常，可能与已有配置文件而参数失效相关。
本软件的帮助文件对此的解决方法是“卸载并重装应用”或者“清除数据”。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
提供一类方案，尽可能在保留应用数据的同时尝试重置应用数据中的MiPush推送配置，以考虑用户保留用户数据的需求，避免重置重配而耗费的时间。

软件的帮助文件可以介绍思路与方法，尝试删除`/data/data/应用包名/shared_prefs`中的`mipush`开头的xml文件（数目不定），以及`XMPushServiceConfig.xml`，然后重开应用。也许有少数应用不同。

如果有意，本软件也可获取root权限，并提供自动或手动（提供说明和选择，过滤掉明显无关的路径、大文件，突出`push`名称）删除此种配置文件的选项。可搭配#174，以及提供在线/内置规则。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
见上。

**Comment by Trumeet** [comment]
感觉这样用户成本比较大（

**Comment by shadowby** [comment]
作者大大有没有考虑下个版本加入什么脚本来清楚数据

**Comment by yfdyh000** [comment]
如果开发成本大，可以只在帮助中提一下该方法的思路。如果推荐应用没问题，可以提供方法和建议，比如MT管理器（2.0）不错，支持递归搜索文件。为了配置繁琐的应用考虑。

最低用户成本是提供选项自动执行删除操作，乃至配有规则，但需要该应用获得root权限。
用本应用的用户，大多不怕折腾吧。

**Comment by shadowby** [comment]
提供功能即可，有root的可以用root方法，没root的寻其他解决办法

**Comment by Trumeet** [comment]
那写文档吧？

**Comment by Trumeet** [comment]
已更新文档。
