### ISSUE TITLE
“应用”列表，小图标模式和查找过滤

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#184]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
* 只是想便于截图（备忘）和查找。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
* 目前列表项大间距，便于点击和阅读，但用户也许会需要紧凑列表。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
* 应用列表和推送记录导出功能。
* 详细表格（注册时间 最后消息 最后通知 等）。
* 详细列表可配合、组合#174，显示有相关监听器但未注册的应用。可以显示“已停用”等状态。

**Additional context**
* 不是很重要，只是个想法。

**Comment by Trumeet** [comment]
比较麻烦 咱不考虑，抱歉。
您是否需要 Fast Scroll？（就是右侧滚动条快速滚动）

**Comment by yfdyh000** [comment]
好的。我觉得简单方案仅需改图标尺寸和间距，上面写的“替代方案”只是想法供参考。
不需要。如果能长到需要滚动块，允许改排序（目前是从旧到新）可能更好，每次查新应用要滚动到底有点麻烦。

**Comment by yfdyh000** [comment]
现已默认显示未注册的应用，应用列表和小图标模式不再需要。本意是用来截图对比已注册的应用与外部查询的有监听器的应用，然后打开应用以注册和排障。
详细表格也不是很重要，普通用户用不上，类似调试级别的东西。“写轮眼”查Push应用的db，能看到大多数技术数据（不过没有注册时间和最后推送）。

那么关掉此问题了。
