### ISSUE TITLE
Xposed 伪装机型改进

### ISSUE THREAD

**Issue by Hill-98** [Trumeet/MiPushFramework#185]
现在的机型伪装是全局的，这样就会造成一些问题。

使用 MiPush 的应用都会在服务里声明 MiPush 的相关服务，是否可以通过检测一个应用有 MiPush 的相关服务，然后对其进行伪装。

**Comment by TimothyZhang023** [comment]
1. 检测并不能保证准确
2. 手动设置非常麻烦 而且没有必要性。
3. 如果觉得xposed 全局不合理，可以使用应用变量代替这个功能。

如果你有什么特别的需求可以评估是不是需要配置在全局白名单中
目前全局白名单主要有谷歌相机和微信

**Comment by Trumeet** [comment]
@TimothyZhang023
Magisk Riru 模块和 Xposed 模块具体实现有区别么？

**Comment by Trumeet** [comment]
不过我觉得倒是可以考虑 QAQ，Riru 模块目前也有这个计划。

**Comment by Trumeet** [comment]
@TimothyZhang023 没具体实现上的区别就行，可以统一配置文件。

**Comment by Trumeet** [comment]
@TimothyZhang023 `handleLoadPackage` 里面读取就可以了吧，不需要启动时读取。

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 `handleLoadPackage` 里面读取就可以了吧，不需要启动时读取。

嗯。启动指的是每个app启动的时候~

**Comment by Hill-98** [comment]
应用变量好像是没兼容 Andorid O，我试了下没效果。

**Comment by TimothyZhang023** [comment]
> 应用变量好像是没兼容 Andorid O，我试了下没效果。

 兼容的，看下左侧菜单，有个什么模式，是要获取root 还有什么临时文件什么的。。我记得要修改一下配置

**Comment by TimothyZhang023** [comment]
fixed with 0.3.6
