### ISSUE TITLE
显示可读的连接日志和概要

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#187]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
即便排除电池优化、锁住Push服务（后台服务保活和保活通知）乃至管理器，仍遇到Push服务后台不时失效。闲置几小时后，打开有MiPush的应用或者管理器，一股脑收到若干个应用的通知。也许与Android的深睡（Doze）有关。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
提供方法以人类可读的方式（面板或整洁概要）查阅服务/长连接的日志和/或保持时间、最后通信时间。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
添加亮屏时唤醒。现有的其他唤醒和网络改变时唤醒可能不足。

**Comment by Trumeet** [comment]
@TimothyZhang023 现有技术可以获得楼主所述的信息吗？我没有研究过小米推送 SDK 具体的长连接部分。

**Comment by TimothyZhang023** [comment]
消息延迟多数是ROM问题。

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 现有技术可以获得楼主所述的信息吗？我没有研究过小米推送 SDK 具体的长连接部分。

mipush 5分钟心跳一次。如果网络异常会重连。如果消息延迟只有两种可能
1. 心跳断了
2. 小米那侧消息积压(目前没怎么看到)

通知栏消息 有个时间。 现在-1分钟-2分钟。。。。表示的就是最后收到消息或者心跳的时间，这个可以自查

**Comment by Trumeet** [comment]
@TimothyZhang023 是指常驻通知？

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 是指常驻通知？

是的

**Comment by Trumeet** [comment]
@TimothyZhang023 请教一下这个是通过什么获取的？

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 请教一下这个是通过什么获取的？

心跳timer会start 一下main service ，那里不是会push这个status 通知么？那个时候会更新时间

**Comment by Trumeet** [comment]
@TimothyZhang023 还有这种操作..

**Comment by Trumeet** [comment]
@TimothyZhang023 是的，但是服务的启动还是小米那里的呀（

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 是的，但是服务的启动还是小米那里的呀（

我们启动 ，那个status 通知是我们push的。。心跳会发一个广播。一个reciever去接，那个reciever我们重写了。所以启动服务是我们的。我们 extend那个原来的类啊，所以通知我们会更新一下。

**Comment by yfdyh000** [comment]
最近没再遇到长连接断掉了。

通知栏消息中那个时间就是我想要的上次通信时间。
如果能形成日志（现有日志太长太详细，也没有内置查看和筛选），可能利于排障。Push启动（持续）时间同上。如果不做，可以关掉此问题了。

**Comment by yfdyh000** [comment]
另外，软件内提供时间，才可以察看关闭“保活通知”后的存活效果。

亮屏时唤醒Push可能得以缓解被终止的情况。

**Comment by TimothyZhang023** [comment]
亮屏时唤醒最新版会加入
通知栏 MiPush status的时间为最后一次唤醒时间

如果遇到推送不及时问题，还是要检查rom或者优化软件是不是 切掉了唤醒途径
