### ISSUE TITLE
vivo nex 权限都开了 试了很多app 可是注册列表一直都是空的

### ISSUE THREAD

**Issue by leeehan** [Trumeet/MiPushFramework#188]
rt 求助…

**Comment by Trumeet** [comment]
Logcat 看一下有没有 Tag 为 `XMPushService Bridge` 的日志

**Comment by leeehan** [comment]
logcat需要root权限 没root 有办法看嘛

**Comment by TimothyZhang023** [comment]
adb logcat 不需要root 


ov 取消电池高级优化

**Comment by Trumeet** [comment]
@leeehan ADB 立即

**Comment by leeehan** [comment]
> 
> 
> adb logcat 不需要root
> 
> ov 取消电池高级优化

之前就取消电池优化试了 还是不行
![default](https://user-images.githubusercontent.com/22447638/46219055-e75e2a00-c378-11e8-92d4-459a4c3f5806.png)

**Comment by leeehan** [comment]
> 
> 
> @leeehan ADB 立即
刚才看了下列表里边出了酷安 不过显示的注册异常 app的日志还有adb抓的日志上传到了云盘
链接：https://share.weiyun.com/52hqfuk 密码：rmd9yf
第一次用adb不知道抓对了没...请见谅

**Comment by Trumeet** [comment]
@leeehan 打不开压缩包（

**Comment by leeehan** [comment]
> 
> 
> @leeehan 打不开压缩包（

刚重新装了下酷安和b站列表里边竟然正常显示了...并且是已注册的状态 又重新装下微店和即刻好像是不行...就是不知道推送是否正常 这几天用着试一下

**Comment by leeehan** [comment]
> 
> 
> @leeehan 打不开压缩包（

直接打开好像有问题 但是应该可以解压
