### ISSUE TITLE
收不到推送

### ISSUE THREAD

**Issue by zzzop** [Trumeet/MiPushFramework#19]
机型红米note4x，系统aex
1软件内一直有注册推送的提示，没见过其他提示
2软件从最近列表划掉再打开推送那个开关就关闭了，这个就是这样的吗？
3软件内的时间戳好像有问题，比如现在10点它显示3点，但是显示“几分钟几小时以前”是正常的

[file.zip](https://github.com/Trumeet/MiPushFramework/files/1270693/file.zip)

**Comment by TimothyZhang023** [comment]
1 2 3 换新版解决。
