### ISSUE TITLE
有消息。有记录，但就是收不到推送！

### ISSUE THREAD

**Issue by straydove** [Trumeet/MiPushFramework#190]
有注册。有消息，有内容。但没有推送

**Comment by TimothyZhang023** [comment]
请提供更多信息。具体提问方法请看项目首页 “如何提问“

> 有注册。有消息，有内容。但没有推送

有注册，请问是什么app
有消息，请问是什么消息
有内容，请问内容是什么

截图 附上应用注册列表 最近活动信息列表 外加日志和系统环境相关信息。
