### ISSUE TITLE
关于可以接受到推送但无法在第三方修改的通知栏上正确显示图标的问题

### ISSUE THREAD

**Issue by kumoilain** [Trumeet/MiPushFramework#191]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）

和issue中的锤子rom一样，在采用了xposed框架（Flat Style Bar Indicator，已上传插件本体+状态栏配置：~[文件](https://pan.baidu.com/s/1Gv9pQU9TC8waBYIeKuAzGg)~）修改状态栏以对抗刘海的Lineage系统上，也出现了类似问题：小米推送服务记录里有收到，下拉通知栏里有通知且合并正常，但是通知栏上没有对应app图标。相关权限均已正确设置。
![qq 20181002130844](https://user-images.githubusercontent.com/29969516/46330427-7ef79d00-c645-11e8-9fc3-eaf0a387b0c4.jpg)
![qq 20181002130848](https://user-images.githubusercontent.com/29969516/46330428-7f903380-c645-11e8-94c1-a1edfb871625.jpg)
![qq 20181002130853](https://user-images.githubusercontent.com/29969516/46330429-7f903380-c645-11e8-9e21-0bd68e563b9b.jpg)
![qq 20181002130856](https://user-images.githubusercontent.com/29969516/46330431-7f903380-c645-11e8-8ff9-a6cb3109e14f.jpg)

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
在使用Flat Style Bar Indicator的情况下，在通知栏上正确显示通知对应的图标。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
我不懂安卓系统原理和编成。但是看了issue之后，是否可以尝试发布一个带空白活动的push服务本体apk？

**Additional context**
小米PocoF1，Lineage15.1，原始系统界面上图标显示正常（虽然大多数时候会被刘海遮住一半，之类的）。

**Comment by TimothyZhang023** [comment]
我理解这个是 使用Flat Style Bar Indicator 造成的问题。
我们暂时处理不了这个兼容问题，这个问题不是应该又Flat Style Bar Indicator 来处理么？

**Comment by kumoilain** [comment]
十分感谢回复。我之前想表达：mipush核心服务保持无活动页、无启动器应用图标显示是否是必要的？以及这是不是同样造成锤子系rom无通知图标的原因。

**Comment by TimothyZhang023** [comment]
> 十分感谢回复。我之前想表达：mipush核心服务保持无活动页、无启动器应用图标显示是否是必要的？以及这是不是同样造成锤子系rom无通知图标的原因。


我是怀疑，但是也没有真机测试。
关于启动器图标提议，yuuta said no。
确实多一个启动器图标不是很优雅 @Trumeet

**Comment by TimothyZhang023** [comment]
0.3.6 已经可以自定义开启 push图标了。
