### ISSUE TITLE
xposed机型模拟在DEV0930上向前兼容

### ISSUE THREAD

**Issue by TimothyZhang023** [Trumeet/MiPushFramework#192]
# xposed机型模拟在DEV0930上向前兼容
* 当前xposed模块开启之后会立即全部启用
* 0930版本可以单独给每个app一个配置开关，但是默认是关闭的
* 老用户升级之后，xposed保持开启，但是app不模拟机型 可能会导致不继续推送的情况

# 方案建议
* 方案1
  * 一个默认开启的全局开关
  * 缺点：不够优雅，增加开关增加使用难度
* 方案2
  * 初始化默认把支持mipush的app开启模拟
  * 问题：后续新装的app 如何解决自动伪装

**Comment by Zxlusersjly** [comment]
请问DEV0930为何还未发布APK吗:sob:？

**Comment by Zxlusersjly** [comment]
@Trumeet 噢，那我就静静期待新版到来吧。

**Comment by TimothyZhang023** [comment]
fixed with 0.3.6
