### ISSUE TITLE
注册异常 提示框的忽略选项

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#193]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
每次进入和刷新应用列表时都会显示。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
* 应该只显示一个。目前有x个注册异常每次就会显示x个对话框。
* 各应用的详情中提供选项，忽略该应用的注册异常。适用于有些应用（酷安、追书神器等），注册后调整某些选项使其会自主取消注册的情况。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
* 应用列表可以分组。分组可以显示数量、折叠、调整排序等。
* 可以提供全局选项及“不再提醒”来禁用此提醒。

**Comment by Trumeet** [comment]
已删除该功能（根据其它 issue）。
分组请单独开 Issue（不要在一个里面塞很多很多问题

**Comment by yfdyh000** [comment]
分组是替代方案的一个想法，不是功能请求，维护者设计可随意。

**Comment by shadowby** [comment]
挺喜欢你的建议，我手机里注册失败的很多，每次进入搜提示，影响体验
