### ISSUE TITLE
前台APP检测模式 作用未说明

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#194]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
设定-前台APP检测模式。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
软件及帮助中未说明该选项和检测的作用。

**Comment by Trumeet** [comment]
检测有助于处理通知点击事件 吧（ @TimothyZhang023

**Comment by TimothyZhang023** [comment]
1. 默认模式 使用 使用数据API  支持 6.0+
2. 兼容模式 使用 无障碍API      

主要原因是原版miui的推送直接在后台startService这个在很多rom上被限制，而且oreo之后禁止这种行为，所以我们先拉起应用（如果应用不再前台）。拉起应用之后，才能startService。 
所有startService必须是app在前台的时候，不然就无法正确跳转，所以我们需要判断谁是当前app。就靠这个功能。

**Comment by yfdyh000** [comment]
建议在软件或帮助中对功能自解释。

拉起应用是哪个应用，push/管理器/需启动应用？startService是什么，点击通知时传递调用数据？

**Comment by TimothyZhang023** [comment]
> 建议在软件或帮助中对功能自解释。
> 
> 拉起应用是哪个应用，push/管理器/需启动应用？startService是什么，点击通知时传递调用数据？

我不认为用户需要关心这个问题，未来肯能会移除这个选项

**Comment by yfdyh000** [comment]
> 我不认为用户需要关心这个问题，未来肯能会移除这个选项

那很好，如果自动检测可靠。

因为用户会有疑问，是否要调整它，它的用途。

**Comment by yfdyh000** [comment]
@Trumeet 如果界面移除，软件中就不需要解释前台检测。
简单说明用途/使用条件即可。

**Comment by yfdyh000** [comment]
选项已有解释。
