### ISSUE TITLE
重复推送的拦截建议

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#195]
## 问题
一些应用(如网易蜗牛读书)，每次推送时都会推送两条相同的内容。
而据酷安评论区，某酷友甚至遇到网易云给他推了四十多条相同内容的通知。
![](https://i.imgur.com/Jqsusuz.jpg)
## 建议
拦截多条同一时间相同内容的非透传通知。仅在通知栏显示一条。
另外，这个拦截功能建议提供每个应用的独立开关。

**Comment by Trumeet** [comment]
推送记录是否显示多条呢？

**Comment by Zxlusersjly** [comment]
@Trumeet 是的
![](https://i.imgur.com/jFTt97f.jpg)

**Comment by yfdyh000** [comment]
如果拦截，是否存在信息的损失（相同内容但可能不同调用）。
已push的通知内容能否修改，能的话x N（但结尾可能被省略）或N x 通知内容，也许更清晰。

**Comment by Zxlusersjly** [comment]
@yfdyh000 确实有可能会造成信息损失，但是这种重复推送的应用毕竟很少，假如分应用拦截后应该不会有太大问题。

**Comment by TimothyZhang023** [comment]
重复消息直接过滤吧

**Comment by Trumeet** [comment]
@TimothyZhang023 @Zxlusersjly @yfdyh000 
觉得需要找出重复通知的根源是什么，直接拦截感觉有点治标不治本（

**Comment by Zxlusersjly** [comment]
@Trumeet 我觉得可能是网易那边的问题，因为目前出现重复通知的我只知道有网易云音乐和网易蜗牛读书

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 @Zxlusersjly @yfdyh000
> 觉得需要找出重复通知的根源是什么，直接拦截感觉有点治标不治本（

发送方的问题。云音乐好像是穿透？但是有标题

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 网易这个应该不是穿透，可能是出于保护隐私的考虑不显示具体内容，而推送类似于“你收到了一条私信”这种消息。

**Comment by yfdyh000** [comment]
@Trumeet 是不是`回掉注册结果（暂时无效）`（回调？）选项的原因，网易没收到反馈就发送了N条通知。

**Comment by yfdyh000** [comment]
> 应该不是吧。这个选项应该没用

我指“暂时无效”是否意味着没有回调。或者是有回调但选项无用，但那样应该隐藏才对。

从`allowReceiveRegisterResult`看，与重复推送似乎关系不大。

**Comment by TimothyZhang023** [comment]
> 我指“暂时无效”是否意味着没有回调。或者是有回调但选项无用，但那样应该隐藏才对。

暂时无效 指的应该是这个选项并不生效。。实际上这个配置开关没有任何用处

**Comment by TimothyZhang023** [comment]
新版有简单重复拦截了
