### ISSUE TITLE
广东移动推送通知BUG

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#197]
广东移动所推送的消息均如图，这是推送框架的问题还是移动的问题？
![](https://i.imgur.com/1RIpwNX.png)

**Comment by TimothyZhang023** [comment]
可能是穿透消息

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 哦，不是BUG就好。

**Comment by Trumeet** [comment]
@Zxlusersjly 能否把推送记录截图发一下？

**Comment by Zxlusersjly** [comment]
@Trumeet 刷了下机，之前的记录已丢失，这是最近的记录。
![](https://i.imgur.com/HrTlsaM.png)

**Comment by TimothyZhang023** [comment]
> @Trumeet 刷了下机，之前的记录已丢失，这是最近的记录。
> ![](https://camo.githubusercontent.com/6ac29ebb24e211589411ebc7a749e49aabd1f28e/68747470733a2f2f692e696d6775722e636f6d2f4872546c73614d2e706e67)

点一下第一条记录看下

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 
@TimothyZhang023 
内容如下(其中含有本人手机号，已删除)
Developer Info:
XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:true, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 01 0B 00 04 00 00 03 D0 C8 1B 13 56 53 DD 51 2E EE 95 C5 FF BB C3 05 54 39 10 B0 35 9D D3 25 95 31 2E DA F8 2F 14 EB 6A 3C CF EA BB 87 35 49 53 FC A7 69 6B C1 2C 0E B4 48 10 CF 43 2B DD 9D F2 AB 5C 6F 98 03 CE 06 B9 3C 0E 89 31 8D E0 9B 2A 1A A2 87 99 0F 23 47 8C A5 FB 46 81 7C 9F 3C 52 6B 14 94 59 AC 66 13 9A B0 67 70 20 E2 2A A2 D7 2D B1..., appid:2882303761517139959, packageName:com.kingpoint.gmcchh, target:Target(channelId:5, userId:59890398209, server:xiaomi.com, resource:an4lGEBI), metaInfo:PushMetaInfo(id:scm51542541227983000u6, messageTs:1541227983000, title:{"title":"10086","alert":"哎呀，流量不多啦！","mail":{"mailId":"OUTERd045f6e16bee4f4892b35442dce06289","title":"哎呀，流量不多啦！","mailType":"2","beginTime":"20181102183148","endTime":"20181105","mailCategory":"3","content":"","funcCode":"GMCCAPP_001_003","funcId":"","remindType":"2","createdTime":"20181102183148","mobileNumber":"隐私内容","adImage":"","dialogImage":"","expireTime":"20181102205959","city":"湛江","brand":"神州行","version":"6.2.1","mailContent":{"contentType":"2","subtitle":"您现在已经使用了5120.00M流量","readingWords":"戳我办理流量特惠吧~","mainContent":{"description":"可用流量为","amount":"0.00","unit":"M"}}}}, description:{"title":"10086","alert":"哎呀，流量不多啦！","mail":{"mailId":"OUTERd045f6e16bee4f4892b35442dce06289","title":"哎呀，流量不多啦！","mailType":"2","beginTime":"20181102183148","endTime":"20181105","mailCategory":"3","content":"","funcCode":"GMCCAPP_001_003","funcId":"","remindType":"2","createdTime":"20181102183148","mobileNumber":"隐私内容","adImage":"","dialogImage":"","expireTime":"20181102205959","city":"湛江","brand":"神州行","version":"6.2.1","mailContent":{"contentType":"2","subtitle":"您现在已经使用了5120.00M流量","readingWords":"戳我办理流量特惠吧~","mainContent":{"description":"可用流量为","amount":"0.00","unit":"M"}}}}, notifyType:1, passThrough:1, notifyId:7700, extra:{mseq=127399991, msgId=1eaa0704-44ca-4ada-b5ac-6626b1cbc5c9, taskId=66620181102}, ignoreRegInfo:false))

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 是不是是否穿透识别错了？

穿透如果有内容我们是直接展现的。。比如酷安那种。。，但是他的内容不太友好
