### ISSUE TITLE
能否将穿透消息传递给应用

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#198]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
比如酷安，目前通知只是显示穿透消息的title，以及点击的效果好像不充分（没有到达指定的板块/页，可能穿透消息携带的信息不足）。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
按正常的设计，将穿透（透传）消息发给所指定的应用，取代现有的元数据通知。如果需要唤醒则还唤醒（能局部更好）。提供应用级选项（权限）来允许，可以默认关闭，也可提供全局的默认选项。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
如果通用不好做、穿透类应用数量不多，可以内置一些配置。
不做也没事，只是突发奇想的改进建议。

**Comment by TimothyZhang023** [comment]
应用需要唤醒才能收到。
默认是应该是会去唤醒。
