### ISSUE TITLE
无障碍-Push 的作用

### ISSUE THREAD

**Issue by yfdyh000** [Trumeet/MiPushFramework#199]
没有提供说明。
能用来替代“保活通知”吗。

**Comment by keith-xiong** [comment]
你到底在关注些什么东西，你是不能用还是怎么滴，老问这样的问题。有什么用设置里不是很清楚吗，这么多人用，开发者还会坑你一个不成…

**Comment by yfdyh000** [comment]
这是个开源项目，我希望它更清晰和易用……
https://github.com/Trumeet/MiPushFramework#%E5%8F%82%E4%B8%8E%E9%A1%B9%E7%9B%AE

**Comment by TimothyZhang023** [comment]
指的是  https://github.com/Trumeet/MiPushFramework/issues/194 这里的辅助模式

**Comment by Trumeet** [comment]
请不要人身攻击。
开源项目不等于要把所有细节都以文档的形式呈现，我们会以用户的角度来审视每一个应用内说明，只有适当的情况下才会被加入。

**Comment by yfdyh000** [comment]
@Trumeet 不是加入文档，是无障碍服务的描述，请参考一下其他软件的无障碍服务，自身可提供描述。Push当前是“没有提供说明”。
例子: https://github.com/ekibun/OpenInWechat/search?q=acc_desc&unscoped_q=acc_desc ，`accessibility-service`中的`android:description`

在酷安已看到至少两例相同的询问。

**Comment by Trumeet** [comment]
@yfdyh000 是这个说明啊.. 可以考虑。
