### ISSUE TITLE
There is no push at all on my phone.

### ISSUE THREAD

**Issue by FoobarRogers** [Trumeet/MiPushFramework#2]
[Log_2017-08-24_19-57-38.txt](https://github.com/Trumeet/MiPushFramework/files/1248719/Log_2017-08-24_19-57-38.txt)
Here is the log, I just do as readme.md says. Can you tell me what is wrong?

**Comment by FoobarRogers** [comment]
08-25 13:31:46.735 D/XMPush  (9353): [Thread:1331] [Slim] read Blob [] Err:Software caused connection abort
08-25 13:31:46.737 D/XMPush  (9353): [Thread:1323] JOB: shutdown the connection. 9, java.net.SocketException: Software caused connection abort
08-25 13:31:46.737 D/XMPush  (9353): [Thread:1323] disconnect 141372120, 143071381
08-25 13:31:46.738 D/XMPush  (9353): 
08-25 13:31:46.738 D/XMPush  (9353): java.net.SocketException: Broken pipe
08-25 13:31:46.738 D/XMPush  (9353): 	at java.net.SocketOutputStream.socketWrite0(Native Method)
08-25 13:31:46.738 D/XMPush  (9353): 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
08-25 13:31:46.738 D/XMPush  (9353): 	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
08-25 13:31:46.738 D/XMPush  (9353): 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
08-25 13:31:46.738 D/XMPush  (9353): 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.slim.d.a(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.slim.d.b(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.slim.f.a(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.smack.h.b(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.push.service.XMPushService.a(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.smack.j.a(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.push.service.XMPushService$h.run(Unknown Source)
08-25 13:31:46.738 D/XMPush  (9353): 	at com.xiaomi.push.service.i$c.run(Unknown Source)
08-25 13:31:46.739 D/XMPush  (9353): [Thread:1323] update the connection status. connected -> disconnected : ERROR_READ_ERROR 
08-25 13:31:46.785 D/XMPush  (9353): [Thread:1323] schedule reconnect in 500ms
08-25 13:31:46.787 D/XMPush  (9353): [Thread:1323] update the client 5 status. binded->unbind CLOSE ERROR_READ_ERROR null null
08-25 13:31:46.974 D/XMPush  (9353): [Thread:1] network changed, no active network
08-25 13:31:46.984 D/XMPush  (9353): [Thread:1323] JOB: disconnect the connection.
08-25 13:31:46.984 D/XMPush  (9353): [Thread:1323] disconnect 141372120, null
08-25 13:31:47.285 D/XMPush  (9353): [Thread:1323] JOB: do reconnect..
08-25 13:31:47.285 D/XMPush  (9353): [Thread:1323] should not connect. quit the job.
08-25 13:31:50.745 D/XMPush  (9353): [Thread:1] network changed, [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "TP-LINK_5G_9FCB", failover: false, available: true, roaming: false, metered: false]
08-25 13:31:50.902 D/XMPush  (9353): [Thread:1323] JOB: do reconnect..
08-25 13:31:50.911 D/XMPush  (9353): [Thread:1323] update the connection status. disconnected -> connecting : ERROR_OK 
08-25 13:31:50.927 D/XMPush  (9353): [Thread:1323] begin to connect to 114.54.23.116:5222
08-25 13:31:51.167 D/XMPushService Bridge(9353): onHandleIntent
08-25 13:31:53.975 D/XMPush  (9353): [Thread:1323] tcp connected
08-25 13:31:53.976 D/XMPush  (9353): [Thread:1323] [slim] open conn: andver=25 sdk=27 hash=_ibqdS49Qkx6NxUq tz=8:0 Model=MI 6 os=782d8b7ac0
08-25 13:31:53.976 D/XMPush  (9353): [Thread:1323] connected to 114.54.23.116:5222 in 3049
08-25 13:31:53.986 D/XMPush  (9353): [Thread:1323] JOB: Handle intent action = com.xiaomi.mipush.SEND_MESSAGE
08-25 13:31:54.023 D/XMPush  (9353): [Thread:1337] setChallenge hash = 5de4e08f
08-25 13:31:54.023 D/XMPush  (9353): [Thread:1337] update the connection status. connecting -> connected : ERROR_OK 
08-25 13:31:54.035 D/XMPush  (9353): [Thread:1323] JOB: bind the client. 5
08-25 13:31:54.036 D/XMPush  (9353): [Thread:1323] update the client 5 status. unbind->binding unknown ERROR_OK null null
08-25 13:31:54.036 D/XMPush  (9353): [Thread:1323] [Slim]: bind id=P2N2n-2
08-25 13:31:54.039 D/XMPush  (9353): [Thread:1337] [Slim] CONN: host = 523c
08-25 13:31:54.078 D/XMPush  (9353): [Thread:1323] SMACK: channel bind succeeded, chid=5
08-25 13:31:54.080 D/XMPush  (9353): [Thread:1323] try send mi push message. packagename:com.netease.cloudmusic action:Command
08-25 13:31:54.081 D/XMPush  (9353): [Thread:1323] update the client 5 status. binding->binded OPEN ERROR_OK null null
08-25 13:31:54.125 D/XMPush  (9353): [Thread:1323] receive a message, appid=2882303761517142681, msgid= nre_57003184588_2882303761517142681

**Comment by FoobarRogers** [comment]
already set brevent as whitelist

**Comment by FoobarRogers** [comment]
08-25 14:56:09.354 I/ActivityManager(1008): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity (has extras)} from uid 10203 on display 0
08-25 14:56:09.445 I/ActivityManager(1008): Start proc 18035:com.xiaomi.xmsf/u0a311 for activity com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity
08-25 14:56:09.446 D/BreventServer(27864): update current to com.xiaomi.xmsf
08-25 14:56:09.479 W/System (18035): ClassLoader referenced unknown path: /data/app/com.xiaomi.xmsf-1/lib/arm64
08-25 14:56:09.606 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 14:56:09.688 D/XMPush (18035): [Thread:1415] load config failure: /data/user/0/com.xiaomi.xmsf/files/XMCloudCfg (No such file or directory)
08-25 14:56:09.716 I/ActivityManager(1008): Displayed com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity: +301ms
08-25 14:56:11.724 D/BreventServer(27864): previous: com.xiaomi.xmsf, packageName: com.android.systemui
08-25 14:56:19.645 W/System (18035): ClassLoader referenced unknown path: /data/user/0/com.xiaomi.xmsf/app_mpcd/lib
08-25 14:57:40.819 D/OkHttp (16200): User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.2; MI 6 Build/NJH47F) (#Build; Xiaomi; MI 6; lineage_oneplus3-userdebug 7.1.2 NJH47F 782d8b7ac0 release-keys; 7.1.2) +CoolMarket/7.9.7
08-25 15:00:24.374 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 15:05:25.361 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 15:10:24.977 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 15:15:25.460 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 15:20:24.365 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 15:25:25.648 E/AlarmManager(1008): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER

**Comment by FoobarRogers** [comment]
你好，log里面发现一个问题：
08-26 21:43:22.019 D/XMPush  (13260): [Thread:1071] load config failure: /data/user/0/com.xiaomi.xmsf/files/XMCloudCfg (No such file or directory)
但用mix plorer查看路径时有这个文件，是什么问题

**Comment by Trumeet** [comment]
我看了下，好像没啥事..

**Comment by Trumeet** [comment]
您自己编译一下目前的最新版，然后看一下推送事件，有没有收到推送

**Comment by Trumeet** [comment]
试试最新的版本，如果还有问题请在 #34 反馈，多谢。
