### ISSUE TITLE
Cant use at OP6 9.0.

### ISSUE THREAD

**Issue by MlgmXyysd** [Trumeet/MiPushFramework#200]
**Describe the bug**
也就是打不开，用不了。

**To Reproduce**
1. 安装Manager
2. 下载框架
3. 提示去App Ops设置后台
4. 点击下一步卡死

**Expected behavior**
正常打开

**Screenshots**
见酷安

**Logs** 
https://pan.baidu.com/s/1Xb1Pa5W-FNJ9egGzk7EqUw (9905)

**ROM and version(manager):**
 - Name: Hydrogen OS
 - Android Version: 9.0
 - Version: 0.3.4.20180808.f235bea

**Additional context**
截图见酷安：https://www.coolapk.com/feed/8520306

**Comment by TimothyZhang023** [comment]
如果root的了。直接卸载appops

一加直接手动设置取消电池优化就可以了。如果不行，卸载appops

**Comment by Trumeet** [comment]
卸载 AppOps？（

**Comment by TimothyZhang023** [comment]
> 卸载 AppOps？（

我一直解决的appops这块有问题。也可能是一加的问题

**Comment by MlgmXyysd** [comment]
@Trumeet @TimothyZhang023 解决了，程序调用magisk授权root的时候卡住了，原因不明，多试几次之后才弹出root授权提示。
