### ISSUE TITLE
关于重复通知抑制 能否针对应用提供单独开关

### ISSUE THREAD

**Issue by lelemka0** [Trumeet/MiPushFramework#206]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
关于重复通知抑制 能否针对应用提供单独开关
*Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
部分应用例如米家（部分智能家居）、工行融e联等的推送内容始终一致，但并不重复。
如米家摄像头的报警始终显示监测区域有变化，工行融e联的大多数推送仅显示您有一条新消息。
重复通知抑制导致部分消息收不到，在米家上尤其明显。
**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
提供一个全局开关关闭通知抑制功能或针对各App提供单独开关。
**Additional context**
Add any other context or screenshots about the feature request here.（更多需要告诉我们的内容）

**Comment by TimothyZhang023** [comment]
后面会改为分钟级抑制。避免误伤

**Comment by TimothyZhang023** [comment]
0.3.6优化
