### ISSUE TITLE
澎湃新闻推送通知丢失相应应用名

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#212]
如图，仅澎湃新闻出现该情况，其他App不会。
![](https://i.imgur.com/k3BoHIX.jpg)

**Comment by TimothyZhang023** [comment]
要注册登录才有推送么？
我放了半天没推送，尴尬。

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 今天确实未有推送[推了几条空白的透传，你可以看下记录有没]，至于是否登录后才会推送，我也不清楚:sweat_smile:

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 现在有一条新推送了，你收到了吗？

**Comment by TimothyZhang023** [comment]
meiyou

**Comment by Zxlusersjly** [comment]
@TimothyZhang023 今晚一共收到2条推送，如果你没有收到，可能是需要登录才可以。。是否需要我提供一个账号给你？

**Comment by TimothyZhang023** [comment]
will be fixed with #211

**Comment by Trumeet** [comment]
@TimothyZhang023 以后可以直接在 Commit message 末尾加 `, close #211`，这样提交完就会自动关联到 Issue 并关闭之。

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 以后可以直接在 Commit message 末尾加 `, close #211`，这样提交完就会自动关联到 Issue 并关闭之。

ok

**Comment by TimothyZhang023** [comment]
fixed with 0.3.6
