### ISSUE TITLE
对Push“移除电池优化”通知的文本建议

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#213]
个人认为，把“移除电池优化”和上方“当您对推送服务启用电池优化后…”的位置对调一下会有更好的展示效果。
[![IMG.jpg](https://i.postimg.cc/43R50vZb/IMG-20181124-101749.jpg)](https://postimg.cc/QFS19TFH)

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 那几个属性确实很乱，容易导致报道有偏差。

我看了下文档。过会儿验一下

**Comment by TimothyZhang023** [comment]
done
