### ISSUE TITLE
关于设置项描述文本的建议

### ISSUE THREAD

**Issue by Zxlusersjly** [Trumeet/MiPushFramework#219]
对设置项中的文字“通过 Xposed 伪装模块或 Magisk 单应用伪装模块，让该应用误认为是小米设备，以增强注册机率（修改需要 ROOT 权限）”的修改建议

- “机率”改为“几率”更符合中国大陆的使用习惯，“机率”多见于台湾与新加坡（←以上是由于本人见“机率”一词过于奇怪而百度得知）；
- “几率”并非“增强”，而应为“增加”或“提高”；
- “让该应用误认为是小米设备”中“该应用”指代不明，且“误认为是小米设备”前缺少主语。

另，以上仅为本人的建议，yfdyh000于#215 中提出了更为可行的建议。

**Comment by yfdyh000** [comment]
本人正在改进该项目的文本，并已完成一大部分，包括本条的改进。PR稍后发出。避免work冲突，所以说一下。
