### ISSUE TITLE
彩云天气没有通知

### ISSUE THREAD

**Issue by fnzyy** [Trumeet/MiPushFramework#236]
Developer Info:
XmPushActionContainer(action:Notification, encryptAction:true, isRequest:true, pushAction:08 00 01 00 00 00 09 02 00 02 01 02 00 03 01 0B 00 04 00 00 70 00 42 46 AE E8 63 21 B2 B7 D6 1E 56 B3 2C 11 D0 8F 18 77 DC 4F 21 6D 7B 45 39 CB 1A 63 5E 40 18 91 7B BE 1D 03 4A 29 5E 1E 55 F1 FA 64 1D 70 74 66 53 87 FB 60 8E 74 9F F9 19 B9 9F 85 95 DE 5C 14 CF 7A C4 5F 8D AB E8 4A 70 35 67 8C B0 0D B6 B0 FD B1 82 8B 84 92 B9 CE DC E0 3C F8 65 7E 89 7D 94 C8 5F DF 0C 36 8C F8 2E 03..., appid:2882303761517170592, packageName:com.nowcasting.activity, target:Target(channelId:5, userId:60188421262, server:xiaomi.com, resource:anJGpH8c), metaInfo:PushMetaInfo(id:dcn_1544081602912, messageTs:0))

记录显示收到通知，通知栏没有推送，另外如果不支持的话，如何让应用自己推送，貌似拒绝注册他自己也不通知了

**Comment by fnzyy** [comment]
对了，另外一个问题，删除小米推送后，注册过的软件如何恢复自己的推送？删除重装吗？

**Comment by yfdyh000** [comment]
卸载重装肯定能恢复。
有些重新打开就可以，会自动注册。拒绝注册就不通知是应用自身的设计。可以用写轮眼-服务，看看应用中mipush相关的服务、监听器是否被应用自身关掉了。

**Comment by TimothyZhang023** [comment]
> Developer Info:
> XmPushActionContainer(action:Notification, encryptAction:true, isRequest:true, pushAction:08 00 01 00 00 00 09 02 00 02 01 02 00 03 01 0B 00 04 00 00 70 00 42 46 AE E8 63 21 B2 B7 D6 1E 56 B3 2C 11 D0 8F 18 77 DC 4F 21 6D 7B 45 39 CB 1A 63 5E 40 18 91 7B BE 1D 03 4A 29 5E 1E 55 F1 FA 64 1D 70 74 66 53 87 FB 60 8E 74 9F F9 19 B9 9F 85 95 DE 5C 14 CF 7A C4 5F 8D AB E8 4A 70 35 67 8C B0 0D B6 B0 FD B1 82 8B 84 92 B9 CE DC E0 3C F8 65 7E 89 7D 94 C8 5F DF 0C 36 8C F8 2E 03..., appid:2882303761517170592, packageName:com.nowcasting.activity, target:Target(channelId:5, userId:60188421262, server:xiaomi.com, resource:anJGpH8c), metaInfo:PushMetaInfo(id:dcn_1544081602912, messageTs:0))
> 
> 记录显示收到通知，通知栏没有推送，另外如果不支持的话，如何让应用自己推送，貌似拒绝注册他自己也不通知了

 这个不叫通知。看到中文通知的记录才算

**Comment by TimothyZhang023** [comment]
![img_20181208_000618_597](https://user-images.githubusercontent.com/3147994/49658475-1bdb1a00-fa7d-11e8-9a45-3c5c32ae1756.jpg)
可以的
推送频率不高？好像赞助之后推送可能会增加？

**Comment by Travisss** [comment]
> 卸载重装肯定能恢复。
> 有些重新打开就可以，会自动注册。拒绝注册就不通知是应用自身的设计。可以用写轮眼-服务，看看应用中mipush相关的服务、监听器是否被应用自身关掉了。

我发现，注册小米推送后，软件自身的XMPushService被自动关掉了

**Comment by TimothyZhang023** [comment]
确认是有推送的，先close了
