### ISSUE TITLE
最新release版要求强制加入电量忽略名单，然而没有这个选项

### ISSUE THREAD

**Issue by IdleCloudWildCrane** [Trumeet/MiPushFramework#239]
手机型号名：360 N4S X20版
型号：1505-A01
Android版本：6.0
ROM名称版本：360OS V2
未使用框架等其他东西
使用的是最新的release版：即0.3.4.20181027
 （ ~~估计是~~）**就是**因为ROM厂商把电量优化的模块删掉了，可是大佬的App强制要求加入忽略名单，所以就很尴尬，没办法启动服务使用这个推送了。。
此手机好像也不能刷机。。

所以希望大佬能取消这个不给加入就不能用的逻辑，感谢

**Comment by yfdyh000** [comment]
最好只提醒一次，而非强制。

**Comment by IdleCloudWildCrane** [comment]
> 最好只提醒一次，而非强制。

提醒几次倒无所谓，每次提醒都没事，但是现在这样直接就排除了某些ROM了，唉

**Comment by Trumeet** [comment]
某些 ROM 不强制不能用，我们才出此下策的。

**Comment by IdleCloudWildCrane** [comment]
> 某些 ROM 不强制不能用，我们才出此下策的。

好吧，谢谢，只好先不用了|･ω･｀)

**Comment by IdleCloudWildCrane** [comment]
> 360系统不是不支持么？启动服务会被干掉的。

所以我是打算打开它自己的电源名单那些的。。

**Comment by TimothyZhang023** [comment]
> 所以我是打算打开它自己的电源名单那些的。。

rom没有这个选项，我觉得即使跳过，使用体验也不会太好。
N4S 可以root的吧。建议刷个MIUI ,逃 )

**Comment by Trumeet** [comment]
@IdleCloudWildCrane 请问最终的实现效果是怎样的？ROM 名称是？（最好您的提供 ROM 下载地址以便我们研究）

**Comment by TimothyZhang023** [comment]
> @IdleCloudWildCrane 请问最终的实现效果是怎样的？ROM 名称是？（最好您的提供 ROM 下载地址以便我们研究）

人家写了的。 360OS 2333333

**Comment by Trumeet** [comment]
@TimothyZhang023 主要是问个版本号，方便去下载对应版本。

**Comment by Trumeet** [comment]
或者楼主帮我把 /system/framework 下的文件提取一下也行..

**Comment by IdleCloudWildCrane** [comment]
> @TimothyZhang023 主要是问个版本号，方便去下载对应版本。

这个。。可以搞，但是你要重新改，太麻烦或者没必要就算了，小众的辣鸡和ROM

**Comment by IdleCloudWildCrane** [comment]
> > 所以我是打算打开它自己的电源名单那些的。。
> 
> rom没有这个选项，我觉得即使跳过，使用体验也不会太好。
> N4S 可以root的吧。建议刷个MIUI ,逃 )

360OS它自己有一个也算是个电源管理名单的东西，我说的是那个，原生的那个确实被阉割掉了QAQ

**Comment by IdleCloudWildCrane** [comment]
> @IdleCloudWildCrane 请问最终的实现效果是怎样的？ROM 名称是？（最好您的提供 ROM 下载地址以便我们研究）

最终实现，no 没有~~最终实现~~，只是不停的弹toast   _(:з」∠)_ 
![2018-12-15-16-20-08](https://user-images.githubusercontent.com/43694364/50040909-11c1a880-0087-11e9-9b4f-74ff119aac2a.png)
![2018-12-15-16-20-38](https://user-images.githubusercontent.com/43694364/50040910-16865c80-0087-11e9-9035-94d5daba3b54.png)

附一个它自己的算是电源管理名单吧
![2018-12-15-16-22-30](https://user-images.githubusercontent.com/43694364/50040926-3cabfc80-0087-11e9-8ff7-c55acbab49a5.png)

**Comment by TimothyZhang023** [comment]
你要找到 PUSH 而不是 小米推送服务

**Comment by IdleCloudWildCrane** [comment]
> 你要找到 PUSH 而不是 小米推送服务

唉，我找了好几遍就是没有

**Comment by yfdyh000** [comment]
> 唉，我找了好几遍就是没有

管理器的高级配置里有一个 Push 图标的选项，勾选。

**Comment by Trumeet** [comment]
@IdleCloudWildCrane 看 Toast 内容应该是阉割掉对应 Activity 了。准备不予修复吧（
@TimothyZhang023 或者干脆去掉这个强制，改为连接失败回退策略？
@IdleCloudWildCrane 还是提供一下吧，外加 `/system/priv-app/com.android.settings` 下的内容，方便我去喷他们（逃

**Comment by IdleCloudWildCrane** [comment]
> @IdleCloudWildCrane 看 Toast 内容应该是阉割掉对应 Activity 了。准备不予修复吧（
> @TimothyZhang023 或者干脆去掉这个强制，改为连接失败回退策略？
> @IdleCloudWildCrane 还是提供一下吧，外加 `/system/priv-app/com.android.settings` 下的内容，方便我去喷他们（逃

没必要就算了别改了，这个真的很小众的，我用旧版本（20180715）的没这个强制的。。而且这个机型可以用360OS V3，不过要丢数据就没升。。
还有就是你要的framework文件我压缩了以后有点大，这里放不了。。
还有
> “/system/priv-app/com.android.settings 下的内容”

是指com.android.settings包名的App，就是系统设置吧，放它的文件夹不是叫这个，我真是...*%#&@..

**Comment by Trumeet** [comment]
@IdleCloudWildCrane 那就找一下 framework.jar、framework.odex 和 framework.vdex，能有的都发来
只是想研究、玩一下（逃
对，就是设定的（

**Comment by IdleCloudWildCrane** [comment]
> @IdleCloudWildCrane 那就找一下 framework.jar、framework.odex 和 framework.vdex，能有的都发来
> 只是想研究、玩一下（逃
> 对，就是设定的（

我只找到jar文件，还有一个好像是360rom的framework文件？不知道，反正我也放进去了。。
[framework.zip](https://github.com/Trumeet/MiPushFramework/files/2685732/framework.zip)

（com.android.settings）CP_SystemSettingMTK的原本列表大致（因为大于10M这里放不了，所以分开了）：
CP_SystemSettingMTK
├─ oat
&nbsp;|&nbsp; &nbsp;└─arm64
&nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; └─CP_SystemSettingMTK.odex
└─ CP_SystemSettingMTK.apk
[01.zip](https://github.com/Trumeet/MiPushFramework/files/2685834/01.zip)
[oat.zip](https://github.com/Trumeet/MiPushFramework/files/2685838/oat.zip)

**Comment by Trumeet** [comment]
@IdleCloudWildCrane emm 这个 framework 是 odex 过的，jar 没有东西.. 算了，先这样吧，我自己看看就得了（
多谢

**Comment by okhowang** [comment]
flyme10也把这个activity阉割了
![Uploading S30606-21095511_com.xiaomi.xmsf.png…]()
