### ISSUE TITLE
无法自启动

### ISSUE THREAD

**Issue by haruhitamako** [Trumeet/MiPushFramework#24]
型号：sony z3+
系统版本：官方7.1.1
问题陈述：重启后服务关闭，不能随系统启动。已经加入电池未优化且没有被绿色。

**Comment by haruhitamako** [comment]
在历史记录选项卡中划掉后会自动转为缓存，然后服务被自杀了。

**Comment by TimothyZhang023** [comment]
服务自启是不可能的，只有靠别的进程拉起，使用后台保活可以防止被杀。
