### ISSUE TITLE
0.3.6.20181130.7881203 通知图标不显示

### ISSUE THREAD

**Issue by qianjie1990** [Trumeet/MiPushFramework#240]
新版本去除了右边应用图标，导致国内通知没有图标了，只显示一个安卓默认的图标
小米mix2s  miui10

**Comment by joyrui** [comment]
同样的问题，据说只能改国际版解决，但我这里国际版无法安装APP

**Comment by qianjie1990** [comment]
> 同样的问题，据说只能改国际版解决，但我这里国际版无法安装APP

虽然miui支持 修改为 原生通知样式，但是不喜欢

**Comment by joyrui** [comment]
> > 同样的问题，据说只能改国际版解决，但我这里国际版无法安装APP
> 
> 虽然miui支持修改为原生通知样式，但是不喜欢

原声通知还是很美丽的，可惜我不能用。

**Comment by Trumeet** [comment]
非常抱歉，这是 MIUI 中国版导致的，请使用其它 ROM 以获得更好地体验。

**Comment by qianjie1990** [comment]
> 非常抱歉，这是 MIUI 中国版导致的，请使用其它 ROM 以获得更好地体验。
非常感谢，很多中国的miui用户，官方的推送无法使用，都在使用你的，这样就无法更新了
