### ISSUE TITLE
改用 xLog 记录日志

### ISSUE THREAD

**Issue by Trumeet** [Trumeet/MiPushFramework#245]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
使用 xLog 记录日志，而不是 Log4a。xLog 具有更多功能，同时可以方便地分日期记录（文件）及打包。

**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）
简化分享日志流程，并分日期记录。于 #80 合并。

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）
曾经考虑过手动分割文件和打包... 嫌麻烦（（

**Additional context**
Add any other context or screenshots about the feature request here.（更多需要告诉我们的内容）
xLog: https://github.com/elvishew/xLog

**Comment by TimothyZhang023** [comment]
daily rolling 会自动清理之前 n 天日志么？

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 那是什么？

按天分隔的话。会保留多少天的？

**Comment by Trumeet** [comment]
七天

**Comment by TimothyZhang023** [comment]
日志清理功能要修改？还是移除？

**Comment by Trumeet** [comment]
@TimothyZhang023 留着也无妨。我改过了
