### ISSUE TITLE
魅蓝3s flyme6使用xp，无法在应用里面显示已经注册推送应用，而且应用检测里面无法检测到米推（实际上有酷安等）

### ISSUE THREAD

**Issue by naloder** [Trumeet/MiPushFramework#25]
18:10:05.758 [Thread-1929] DEBUG top.trumeet.mipushframework.c.a - shouldAllow ->CONTENT
18:10:05.763 [Thread-1929] WARN  top.trumeet.mipushframework.c.a - Allowed: null, pkg=com.android.providers.settings
18:10:05.873 [Thread-1929] DEBUG top.trumeet.mipushframework.c.a - shouldAllow ->CONTENT
18:10:05.874 [Thread-1929] WARN  top.trumeet.mipushframework.c.a - Allowed: null, pkg=com.android.providers.settings
18:10:05.885 [Thread-1929] DEBUG PushCore - [Thread:1929] Don't send message before initialization succeeded!
18:10:06.303 [main] DEBUG PushCore - [Thread:1] Don't send message before initialization succeeded!
18:10:06.387 [Connection Controller Thread] DEBUG PushCore - [Thread:1937] JOB: prepare the mi push account.
18:10:06.398 [main] DEBUG PushCore - [Thread:1] XMPushService created pid = 13184
18:10:06.401 [Connection Controller Thread] DEBUG PushCore - [Thread:1937] JOB: Handle intent action = com.xiaomi.mipush.REGISTER_APP
18:10:06.404 [main] DEBUG PushCore - [Thread:1] Service destroyed
18:10:06.426 [Connection Controller Thread] DEBUG PushCore - [Thread:1937] JOB: disconnect for service destroy.
18:10:06.427 [Connection Controller Thread] DEBUG PushCore - [Thread:1937] JOB: ask the job queue to quit
18:10:07.443 [Thread-1940] DEBUG PushCore - [Thread:1940] Could not send  register message within 5s repeatly .
18:10:07.455 [Connection Controller Thread] DEBUG PushCore - [Thread:1941] JOB: prepare the mi push account.
18:10:07.460 [main] DEBUG PushCore - [Thread:1] XMPushService created pid = 13184
18:10:07.462 [main] DEBUG PushCore - [Thread:1] network changed, [type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: cmnet, roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
18:10:07.470 [Connection Controller Thread] DEBUG PushCore - [Thread:1941] JOB: do reconnect..
18:10:07.472 [Connection Controller Thread] DEBUG PushCore - [Thread:1941] should not connect. quit the job.
18:10:31.093 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.gba.GbaService
18:10:31.094 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.gba not have push service!
18:10:31.094 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.ppl.PplService
18:10:31.094 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.ppl not have push service!
18:10:31.094 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.sorcerer.sorcery.iconpack not have push service!
18:10:31.095 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.gd.mobicore.pa.service.ProvisioningService
18:10:31.095 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.gd.mobicore.pa.service.DeveloperService
18:10:31.096 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.gd.mobicore.pa.service.OemService
18:10:31.096 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.gd.mobicore.pa not have push service!
18:10:31.097 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> org.simalliance.openmobileapi.uicc2terminal.Uicc2Terminal
18:10:31.097 [AsyncTask #2] ERROR CheckSupportUtils - Pkg org.simalliance.openmobileapi.uicc2terminal not have push service!
18:10:31.098 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.providers.telephony not have push service!
18:10:31.098 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.documentsui not have push service!
18:10:31.099 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.baidu.location.f
18:10:31.099 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.NormalUpdateService
18:10:31.099 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.TodayForecastUpdateService
18:10:31.100 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.TomorrowForecastUpdateService
18:10:31.100 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.PollingService
18:10:31.100 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.ProtectService
18:10:31.101 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> wangdaye.com.geometricweather.service.TileService
18:10:31.101 [AsyncTask #2] ERROR CheckSupportUtils - Pkg wangdaye.com.geometricweather not have push service!
18:10:31.101 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.calendar.EmptyService
18:10:31.101 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.calendar.CalendarReceiver$RemoveScheduledAlarmsEmptyService
18:10:31.102 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.calendar.CalendarProviderIntentService
18:10:31.102 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.providers.calendar not have push service!
18:10:31.102 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.media.MediaScannerService
18:10:31.102 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.media.MtpService
18:10:31.102 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.providers.media not have push service!
18:10:31.103 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.flyme.hometools not have push service!
18:10:31.103 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.android.onetimeinitializer.OneTimeService
18:10:31.103 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.google.android.onetimeinitializer not have push service!
18:10:31.103 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.fwk.plugin not have push service!
18:10:31.103 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> ml.puredark.hviewer.download.DownloadService
18:10:31.103 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.lzy.okserver.download.DownloadService
18:10:31.103 [AsyncTask #2] ERROR CheckSupportUtils - Pkg ml.puredark.hviewer not have push service!
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> eu.chainfire.flash.ui.misc.BootCompleteService
18:10:31.104 [AsyncTask #2] ERROR CheckSupportUtils - Pkg eu.chainfire.flash not have push service!
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mxtech.media.service.FFService
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mxtech.videoplayer.service.PlayService
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.android.gms.measurement.AppMeasurementService
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.android.gms.measurement.AppMeasurementJobService
18:10:31.104 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.firebase.iid.FirebaseInstanceIdService
18:10:31.105 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mxtech.videoplayer.pro not have push service!
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.animatorservice.MzAnimatorService
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.launcher.MemoryTracker
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.105 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.flyme.launcher not have push service!
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.sogou.SogouIME
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.internet.NotifyProgressService
18:10:31.105 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.multimedia.TransferService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sogou.passportsdk.service.PassportUploadService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.settings.status.SogouStatusService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.settings.InstallThemeService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwordsbase.entrance.HotwordsBaseEntranceService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwordsbase.mini.download.DownloadService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.homefloating.HotwordsHomeFloatingWindowService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.floatingpopup.HotwordsPushFloatingWindowService
18:10:31.106 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.fixednotification.HotwordsFixedNotificationService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.clipboardpopup.HotwordsClipboardService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.clipboardpopup.HotwordsClipboardFloatingWindow
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.entrance.HotwordsExtendEntranceService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.upush.HotwordsExtendPushService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.browser.HotwordsSemobWakeUpService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sogou.udp.push.PushService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sogou.udp.push.SGPushMessageService
18:10:31.107 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.sohu.inputmethod.sogou.push.PushReceiveService
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> sogou.mobile.explorer.hotwords.floatingpopup.PushFloatingWindowService
18:10:31.108 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.sohu.inputmethod.sogou not have push service!
18:10:31.108 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.wallpapercropper not have push service!
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.launcher3.MemoryTracker
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.teslacoilsw.launcher.NovaService
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.teslacoilsw.launcher.NovaAccessibilityService
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.teslacoilsw.launcher.notificationlistener.NotificationListener
18:10:31.108 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.android.gms.measurement.AppMeasurementService
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.android.gms.measurement.AppMeasurementJobService
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.google.firebase.iid.FirebaseInstanceIdService
18:10:31.109 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.teslacoilsw.launcher not have push service!
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.tencent.bugly.beta.tinker.TinkerResultService
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.tencent.tinker.lib.service.TinkerPatchService
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.tencent.tinker.lib.service.TinkerPatchService$InnerService
18:10:31.109 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.tencent.tinker.lib.service.DefaultTinkerResultService
18:10:31.109 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.zdy.project.wechat_chatroom_helper not have push service!
18:10:31.110 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.110 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.110 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.backup.compontent.BackupRestoreService
18:10:31.110 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.desktopbackup not have push service!
18:10:31.110 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> org.simalliance.openmobileapi.service.SmartcardService
18:10:31.110 [AsyncTask #2] ERROR CheckSupportUtils - Pkg org.simalliance.openmobileapi.service not have push service!
18:10:31.110 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.activate.activatephone.ActivatePhoneService
18:10:31.110 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.activate.activatephone not have push service!
18:10:31.111 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.account.pay.service.MzSystemPayService
18:10:31.111 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.111 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.111 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.upay.billing.sdk.LocalService
18:10:31.111 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.account.pay not have push service!
18:10:31.111 [AsyncTask #2] ERROR CheckSupportUtils - Pkg me.seasonyuu.xposed.networkspeedindicator.h2os not have push service!
18:10:31.111 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.externalstorage not have push service!
18:10:31.112 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.alarmclock.alarms.AlarmService
18:10:31.112 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.alarmclock.timer.TimerRingService
18:10:31.112 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.alarmclock.stopwatch.StopwatchService
18:10:31.113 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.113 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.113 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.alarmclock.festival.FestivalService
18:10:31.113 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.alarmclock.utils.ForceTouchHelper$ForceTouchService
18:10:31.113 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.alarmclock not have push service!
18:10:31.114 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> cn.wq.myandroidtoolspro.recyclerview.fragment.current.ActivityWatchingService
18:10:31.114 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> cn.wq.myandroidtoolspro.recyclerview.fragment.current.FragmentWatchingService
18:10:31.114 [AsyncTask #2] ERROR CheckSupportUtils - Pkg cn.wq.myandroidtoolspro not have push service!
18:10:31.114 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.ygps.YgpsService
18:10:31.115 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.ygps not have push service!
18:10:31.115 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.htmlviewer not have push service!
18:10:31.115 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.iflytek.speechsuite.binder.SuiteBinderService
18:10:31.115 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.iflytek.business.download.impl.DownloadService
18:10:31.115 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.iflytek.business.download.DownloadHandlerService
18:10:31.115 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.iflytek.speechsuite not have push service!
18:10:31.116 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.powersave.NotificationListenerService
18:10:31.116 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.powersave not have push service!
18:10:31.116 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.mms.service.MmsService
18:10:31.116 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.mms.utils.SmsReceiverService
18:10:31.116 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.mms.service not have push service!
18:10:31.116 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.coderstory.toolkit not have push service!
18:10:31.116 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.providers.downloads.DownloadService
18:10:31.116 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.android.providers.downloads not have push service!
18:10:31.117 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.mzsimcontacts.MzSimContactsService
18:10:31.117 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.mzsimcontacts not have push service!
18:10:31.118 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.operation.FileOperationService
18:10:31.118 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.operation.FileExtractService
18:10:31.118 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.volume.VolumeService
18:10:31.118 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.EventIntentService
18:10:31.119 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.FileManagerIntentService
18:10:31.119 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.119 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.119 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.remote.ftpserver.swiftp.FsService
18:10:31.119 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.security.EncryptService
18:10:31.120 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.mediascan.ScanService
18:10:31.120 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.flyme.filemanager.recycled.GarbageClearService
18:10:31.120 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.meizu.filemanager not have push service!
18:10:31.120 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.wifi.WifiStateListener
18:10:31.121 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.cpustress.CpuStressTestService
18:10:31.121 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.nonsleep.EMWakeLockService
18:10:31.121 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.lte.CommandToolService
18:10:31.121 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.boot.EmBootStartService
18:10:31.121 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.engineermode.modemnotification.ModemNotificationService
18:10:31.122 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.engineermode not have push service!
18:10:31.122 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.mediatek.omacp.message.OmacpReceiverService
18:10:31.122 [AsyncTask #2] ERROR CheckSupportUtils - Pkg com.mediatek.omacp not have push service!
18:10:31.122 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.update.service.MzUpdateComponentService
18:10:31.123 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.meizu.cloud.pushsdk.NotificationService
18:10:31.123 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.opera.android.turbo.TurboService
18:10:31.123 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.android.browser.media.MediaPlayerService
18:10:31.124 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.amap.api.location.APSService
18:10:31.124 [AsyncTask #2] DEBUG CheckSupportUtils - Service name -> com.zhangyue.iReader

**Comment by Trumeet** [comment]
这个 feature 已经弃坑了，下个版本删了，抱歉
