### ISSUE TITLE
不知道作者什么时候可以修复一下bug

### ISSUE THREAD

**Issue by heartacker** [Trumeet/MiPushFramework#26]
劳烦了。谢谢

**Comment by kotomei** [comment]
在提出 issue 时，请注明出现了什么 bug
毕竟我们也不一定可以复现您所出现的问题：）
我们更不可能亲自拿到您的设备，从而得以知道有什么问题
个人强烈建议您阅读 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md) ，这也许会对您以后的学习工作中起到不小的帮助

**Comment by Trumeet** [comment]
是什么 bug 呢.. 很抱歉太长时间没有维护这个项目，给您带来的不变敬请谅解。
