### ISSUE TITLE
移除电池优化无限循环

### ISSUE THREAD

**Issue by heartacker** [Trumeet/MiPushFramework#28]
CheckDozeActivity.java  

if (!PushServiceAccessibility.isInDozeWhiteList(this) &&
                Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            Intent intent = new Intent();
            String packageName = getPackageName();
            intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
            intent.setData(Uri.parse("package:" + packageName));
            startActivity(intent);
        } else {
            nextPage();
        }

这里不知道为什么。调试结果显示
Build.VERSION.SDK_INT = Build.VERSION_CODES.M=23，所以导致这里无限循环了

**Comment by Trumeet** [comment]
你的 ROM 版本是...

**Comment by heartacker** [comment]
smartisan os 。Android 是6.0.1.

**Comment by shuohao** [comment]
我的也是锤子坚果Pro  安卓7.1.1

**Comment by Trumeet** [comment]
@heartacker 自己单独
```java
Intent intent = new Intent();
String packageName = getPackageName();
intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
intent.setData(Uri.parse("package:" + <自己的包名>));
startActivity(intent);
```
会发生什么呢..

**Comment by Trumeet** [comment]
#6 已修复。
