### ISSUE TITLE
记录里显示收到推送，但实际并没有。

### ISSUE THREAD

**Issue by cv0cv0** [Trumeet/MiPushFramework#29]
还有用了magisk并没有用，很多带了XMPushService的软件依然启用自己的服务。

**Comment by eroneko** [comment]
我这里也是，即刻推送很多次，但是并没有通知，另外也无法接管京东的推送

**Comment by Trumeet** [comment]
那个是软件自己的锅，我也没有精力来逐个分析每个 App，那种的就算了吧（逃跑
