### ISSUE TITLE
曾经miui会推送的很多app现在不推送

### ISSUE THREAD

**Issue by BlessWz** [Trumeet/MiPushFramework#3]
开了matlog，但是过一会前面的日志会自动消失，不知道怎么回事。于是只截到了这么短一段。
红米4x rr7.1.2 这个app后台正常，显示“一个进程”
黑域了微博，本来miui时，ipad和手机同时收到微博消息，现在手机收不到
08-25 11:25:11.252 I/ActivityManager(1356): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity bnds=[0,692][180,852] (has extras)} from uid 10197 on display 0
08-25 11:26:12.108 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER
08-25 11:27:32.310 D/BreventServer(12097): update current to com.xiaomi.xmsf
08-25 11:27:32.310 D/BreventServer(12097): previous: com.gh4a, packageName: com.xiaomi.xmsf
08-25 11:27:32.367 D/bootingxapp(2937): CLEAR event: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity dev: Xiaomi
08-25 11:27:32.367 D/bootingx (2937): --- event sent: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity
08-25 11:27:34.374 D/BreventServer(12097): previous: com.xiaomi.xmsf, packageName: com.teslacoilsw.launcher
08-25 11:28:45.352 D/BreventServer(12097): update current to com.xiaomi.xmsf
08-25 11:28:45.352 D/BreventServer(12097): previous: com.android.systemui, packageName: com.xiaomi.xmsf
08-25 11:28:45.394 D/bootingxapp(2937): CLEAR event: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity dev: Xiaomi
08-25 11:28:45.395 D/bootingx (2937): --- event sent: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity
08-25 11:29:10.990 D/BreventServer(12097): update current to com.xiaomi.xmsf
08-25 11:29:10.991 D/BreventServer(12097): previous: com.gh4a, packageName: com.xiaomi.xmsf
08-25 11:29:11.038 D/bootingxapp(2937): CLEAR event: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity dev: Xiaomi
08-25 11:29:11.038 D/bootingx (2937): --- event sent: com.xiaomi.xmsf class name: top.trumeet.mipushframework.settings.MainActivity
08-25 11:29:13.041 D/BreventServer(12097): previous: com.xiaomi.xmsf, packageName: com.android.systemui

**Comment by Trumeet** [comment]
噗.. 这里面每一行有用的（（
您把 matlog 设置 tag（没怎么用过，应该可以的） `Xiaomi`，然后应该不会滚动 吧..
然后把那里的发过来？

**Comment by BlessWz** [comment]
是搜索xiaomi标签吗？不知道对不对，还是不行的话算了，大不了不用了ԅ(¯ㅂ¯ԅ)
08-25 11:04:47.400 F/DEBUG (5750): Build fingerprint: 'Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys' 08-25 12:11:12.927 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER 08-25 12:16:12.094 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER 08-25 12:19:48.943 W/PackageManager(1356): Failed setComponentEnabledSetting: component class com.xiaomi.push.service.XMPushService does not exist in org.fungo.fungolive 08-25 12:19:51.536 I/BroadcastQueue(1356): Delay finish: com.tudou.android/org.android.agoo.xiaomi.MiPushBroadcastReceiver 08-25 12:20:41.276 W/ActivityManager(1356): Unable to start service Intent { act=com.xiaomi.xmsf.push.ACCOUNT_CHANGE pkg=com.duokan.reader } U=0: not found 08-25 12:21:12.098 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER 08-25 12:26:12.104 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER 08-25 12:29:35.199 D/OkHttp (16777): User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.2; Redmi 4X Build/NJH47F) (#Build; Xiaomi; Redmi 4X; lineage_santoni-userdebug 7.1.2 NJH47F 1c0d1bc5ad release-keys; 7.1.2) +CoolMarket/7.9.7 08-25 12:29:35.220 D/OkHttp (16777): User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.2; Redmi 4X Build/NJH47F) (#Build; Xiaomi; Redmi 4X; lineage_santoni-userdebug 7.1.2 NJH47F 1c0d1bc5ad release-keys; 7.1.2) +CoolMarket/7.9.7 08-25 12:29:37.578 D/bootingxapp(2937): CLEAR event: com.nolanlawson.logcat class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:29:39.409 D/bootingxapp(2937): CLEAR event: com.topjohnwu.magisk class name: com.topjohnwu.magisk.superuser.SuRequestActivity dev: Xiaomi 08-25 12:29:39.415 D/bootingxapp(2937): CLEAR event: com.nolanlawson.logcat class name: android.app.ProgressDialog dev: Xiaomi 08-25 12:29:55.156 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:29:56.069 D/bootingxapp(2937): CLEAR event: com.android.vending class name: com.google.android.finsky.activities.MainActivity dev: Xiaomi 08-25 12:29:57.095 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:29:58.590 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: com.pluscubed.logcat.ui.LogcatActivity dev: Xiaomi 08-25 12:30:06.079 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:30:08.899 D/bootingxapp(2937): CLEAR event: com.google.android.gm class name: com.google.android.gm.ui.MailActivityGmail dev: Xiaomi 08-25 12:30:19.109 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:30:20.284 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: android.support.v7.app.b dev: Xiaomi 08-25 12:30:21.918 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:30:23.054 D/OkHttp (16777): User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.2; Redmi 4X Build/NJH47F) (#Build; Xiaomi; Redmi 4X; lineage_santoni-userdebug 7.1.2 NJH47F 1c0d1bc5ad release-keys; 7.1.2) +CoolMarket/7.9.7 08-25 12:30:32.961 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:30:55.592 D/bootingxapp(2937): CLEAR event: com.google.android.googlequicksearchbox class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:30:55.855 D/bootingxapp(2937): CLEAR event: com.teslacoilsw.launcher class name: com.teslacoilsw.launcher.NovaLauncher dev: Xiaomi 08-25 12:30:56.779 D/bootingxapp(2937): CLEAR event: mark.via class name: mark.via.ui.activity.BrowserActivity dev: Xiaomi 08-25 12:30:59.455 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:30:59.760 D/bootingxapp(2937): CLEAR event: mark.via class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:31:00.905 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:31:12.107 E/AlarmManager(1356): RTC Alarm: 0 null com.xiaomi.xmsf com.xiaomi.push.PING_TIMER 08-25 12:31:27.788 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:31:28.675 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: com.pluscubed.logcat.ui.LogcatActivity dev: Xiaomi 08-25 12:31:29.669 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:31:33.076 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:31:48.113 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:32:15.162 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:32:27.947 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:32:30.017 D/bootingxapp(2937): CLEAR event: com.google.android.gm class name: com.google.android.gm.ui.MailActivityGmail dev: Xiaomi 08-25 12:32:40.551 V/xiaomi (16777): [Thread:1015] receive an intent from server, action=com.xiaomi.mipush.RECEIVE_MESSAGE 08-25 12:32:40.598 V/xiaomi (16777): [Thread:1015] processing a message, action=SendMessage 08-25 12:32:40.607 D/XMPush (31088): [Thread:1127] JOB: Handle intent action = com.xiaomi.mipush.SEND_MESSAGE 08-25 12:32:40.612 V/xiaomi (16777): [Thread:1015] receive a message, msgid=ulm07b01503635560368Fs, jobkey=ulm07b01503635560368Fs 08-25 12:32:44.048 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:32:45.993 D/bootingxapp(2937): CLEAR event: mark.via class name: mark.via.ui.activity.BrowserActivity dev: Xiaomi 08-25 12:33:21.670 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:33:25.971 V/xiaomi (16777): [Thread:1016] receive an intent from server, action=com.xiaomi.mipush.RECEIVE_MESSAGE 08-25 12:33:26.001 V/xiaomi (16777): [Thread:1016] processing a message, action=SendMessage 08-25 12:33:26.003 D/XMPush (31088): [Thread:1127] JOB: Handle intent action = com.xiaomi.mipush.SEND_MESSAGE 08-25 12:33:26.020 V/xiaomi (16777): [Thread:1016] receive a message, msgid=ucm04b53503635605608xF, jobkey=ucm04b53503635605608xF 08-25 12:34:19.507 D/bootingxapp(2937): CLEAR event: com.android.systemui class name: com.android.systemui.recents.RecentsActivity dev: Xiaomi 08-25 12:34:21.112 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: com.pluscubed.logcat.ui.LogcatActivity dev: Xiaomi 08-25 12:34:21.176 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi 08-25 12:34:31.491 D/bootingxapp(2937): CLEAR event: com.pluscubed.matlog class name: android.widget.FrameLayout dev: Xiaomi 08-25 12:34:44.693 D/bootingxapp(2937): CLEAR event: com.baidu.input class name: android.inputmethodservice.SoftInputWindow dev: Xiaomi

**Comment by BlessWz** [comment]
我去，变得好乱

**Comment by BlessWz** [comment]
抱歉，实在太乱了，我还是截图酷安私信给你吧，麻烦你了
