### ISSUE TITLE
关于状态栏提示

### ISSUE THREAD

**Issue by cooowha** [Trumeet/MiPushFramework#31]
作者好，我发现我现在的系统，当我的状态栏最左边已经有图标了的时候，就不会有通知，包括小图标和通知栏。当是空的时候就会有了，同时通知栏也会出现。但是一个应用就算有多条消息，也只显示一条。不过应用角标是显示正常的数目

**Comment by cooowha** [comment]
手机是三星s6

**Comment by Trumeet** [comment]
通知栏左侧是什么图标

**Comment by cooowha** [comment]
好像又不是这个问题。一会有一会没有的也是。。搞不懂了。。还有一个就是记录里面的时间会刷的不对，第一时间显示的时间是标准时的时间，不是+8的。过一会又是+8的时间。不知道是否是这个原因造成的。。

**Comment by cooowha** [comment]
看时间，不知道是不是不推送的原因
![](http://ww4.sinaimg.cn/large/0060lm7Tly1fmfj1xgi7qj30u01hc43z.jpg)

**Comment by Trumeet** [comment]
不是，统一都是 UTC 时间。
