### ISSUE TITLE
检查运行状态成功后，点next闪了一下又重新检查运行状态

### ISSUE THREAD

**Issue by shuohao** [Trumeet/MiPushFramework#36]
如题,在看到修改什么的界面的时候闪了一下，锤子坚果Pro 安卓7.1.1

**Comment by Trumeet** [comment]
可以正常进入吗？

**Comment by shuohao** [comment]
![1](https://user-images.githubusercontent.com/4637107/35615737-0d7e161a-06ae-11e8-8511-943973df4647.png)
![2](https://user-images.githubusercontent.com/4637107/35615740-0e19d172-06ae-11e8-9dce-2b8441bd6b47.png)
![3](https://user-images.githubusercontent.com/4637107/35615750-14fb1b04-06ae-11e8-9975-57608ed24a90.png)

点next然后从第二张闪了一下修改深度伪装那个页面就回到第一张图那个页面

**Comment by Trumeet** [comment]
正常，不用管。闪过去说明不用管。

**Comment by shuohao** [comment]
老哥 不是闪过去都下一页 而是又回到第一页也就是无法往下进行 无限循环啊

**Comment by shuohao** [comment]
我贴的图里第一页是不是你说的主界面？

**Comment by tuhaonan** [comment]
锤子m1l上 也存在同样问题

**Comment by TIANKONGSANG** [comment]
荣耀8 Android7.0 同样的

**Comment by TIANKONGSANG** [comment]
重启 卡进去了

**Comment by laosb** [comment]
1393b30-SNAPSHOT 可以在 SmartisanOS 4.1.2 的坚果 Pro 上正常运行了。

**Comment by shuohao** [comment]
这个issue可以关闭了
