### ISSUE TITLE
锤子手机依旧无限重复循环无法进入程序。

### ISSUE THREAD

**Issue by heartacker** [Trumeet/MiPushFramework#39]
检查运行状态之后
进入修改buil.prop 深度伪装MIUI这里会自动跳过，然后再次进入“检查运行状态”

就这样无线循环

![gif_20180131_205001](https://user-images.githubusercontent.com/1876302/35623953-6405bc94-06c8-11e8-8b51-de2d59cdc023.gif)

**Comment by Trumeet** [comment]
和 #36 一样，等待修复，抱歉
