### ISSUE TITLE
Matlog设置XMPUSH过滤，后台有即刻和酷安

### ISSUE THREAD

**Issue by JackieMium** [Trumeet/MiPushFramework#4]
已经按照README设置好，即刻和酷安在后台运行，看到酷安的XMPUSH也自动禁用了。

```
08-25 14:31:26.468 D/XMPush  (6586): [Thread:1] Service called on timer
08-25 14:31:26.470 D/XMPush  (6586): [Thread:411] [Slim] SND ping id=0
08-25 14:31:26.499 D/XMPush  (6586): [Thread:512] [Slim] RCV ping id=0
08-25 14:31:32.421 D/XMPushService Bridge(6586): onHandleIntent
08-25 14:31:32.427 W/ActivityManager(1611): Unable to start service Intent { cmp=com.ruguoapp.jike/com.xiaomi.push.service.XMPushService } U=0: not found
08-25 14:31:36.476 D/XMPush  (6586): [Thread:411] JOB: check the ping-pong.1503642686470
08-25 14:36:26.482 D/XMPush  (6586): [Thread:1] Service called on timer
08-25 14:36:26.491 D/XMPush  (6586): [Thread:411] [Slim] SND ping id=0
08-25 14:36:26.520 D/XMPush  (6586): [Thread:512] [Slim] RCV ping id=0
08-25 14:36:36.496 D/XMPush  (6586): [Thread:411] JOB: check the ping-pong.1503642986490
``` 

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Trumeet** [comment]
看样子服务的推送运行正常的.. 您把 正在运行的服务 截图我看一下？

**Comment by JackieMium** [comment]
@Trumeet 服务肯定是在的，我确认过
![](http://i.imgur.com/uufGWte.png)


_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chengyuhui** [comment]
即可确实禁用了XMPushService，但是启用了个推的服务

**Comment by JackieMium** [comment]
@chengyuhui 然后呢？

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Trumeet** [comment]
还不是很懂你的问题.. 即刻和酷安在后台，酷安的XMPushService禁用了？禁用了还怎么在后台_(:з)∠)_

**Comment by JackieMium** [comment]
@Trumeet 我的意思是说，通过MAT可以看到酷安的米推已经自动禁用了。
你的意思是说，应该不把酷安放在后台？直接退出掉然后来测试推送？

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Trumeet** [comment]
@JackieMium 不用的，禁用了说明工作中（
