### ISSUE TITLE
关于在某些Oreo设备无法后台运行的问题

### ISSUE THREAD

**Issue by chaoes** [Trumeet/MiPushFramework#40]
在某些Oreo(如HOs,OOs)设备上xmsf service关闭电池优化后也无法在后台运行,但是绿色守护设置-疑难解决-服务守护选项勾选后可以在这些ROM上常驻后台，建议参考绿色守护。
或者给xmsfservic一个主活动，这样在任务界面锁住也可以使其常驻后台。

**Comment by Trumeet** [comment]
这些 ROM 有没有后台管理之类的

**Comment by chaoes** [comment]
只有省电优化

**Comment by Trumeet** [comment]
是 ROM 自己的？

**Comment by chaoes** [comment]
看着是和aosp一样的

**Comment by TimothyZhang023** [comment]
rom自带杀进程能力可以用新版保活机制 后台锁住一个空ac实现了。
