### ISSUE TITLE
一加5T氧os open beta3 无法启动服务

### ISSUE THREAD

**Issue by snipking** [Trumeet/MiPushFramework#48]
卡在允许后台服务这一步，已经关闭电池优化，打开自启动，关闭电池-高级优化，允许后台活动，但还是不行

系统 氧os open beta 3(oreo 8.0.0)

MiPushFramework 0.3.1.Alpha

(试过 0.3.Alpha 版本是正常的)

**Comment by EwanZhang** [comment]
一加3，氢8.0也是这样

**Comment by Trumeet** [comment]
您用 AppOps 获取一下 “在后台运行或被唤醒” 的值？

**Comment by Alex4me** [comment]
![screenshot_20180208-212459](https://user-images.githubusercontent.com/19247887/35975167-c011faa8-0d16-11e8-9768-247358594fd5.jpg)
一加5 H2OS Open Beta 4

**Comment by Trumeet** [comment]
手动执行以下命令（root）：
```shell
appops get com.xiaomi.xmsf 63
```

**Comment by KWidLuK** [comment]
同手机、系统、问题，要不我来进行后续反馈吧
255|OnePlus5T:/data/data/com.termux/files/home #
appops get com.xiaomi.xmsf 63
No operations.
ppops get com.xiaomi.xmsf                             <
VIBRATE: allow; time=+3m48s558ms ago; duration=+372ms
READ_EXTERNAL_STORAGE: allow; time=+20m52s362ms ago
WRITE_EXTERNAL_STORAGE: allow; time=+20m52s362ms ago
RUN_IN_BACKGROUND: allow; time=+3m49s484ms ago
AUTO_START: allow; time=+41m51s67ms ago
OnePlus5T:/data/data/com.termux/files/home #

**Comment by TimothyZhang023** [comment]
新版应该可以了
