### ISSUE TITLE
到目前为止，还没有收到过push

### ISSUE THREAD

**Issue by qq412524875** [Trumeet/MiPushFramework#5]
[logcat.txt](https://github.com/Trumeet/MiPushFramework/files/1251337/logcat.txt)
[device_info.txt](https://github.com/Trumeet/MiPushFramework/files/1251338/device_info.txt)

**Comment by qq412524875** [comment]
[logcat.txt](https://github.com/Trumeet/MiPushFramework/files/1251344/logcat.txt)

**Comment by 1176020631** [comment]
我也是！！

**Comment by rightmans** [comment]
只有前台才给推送

**Comment by Trumeet** [comment]
日志里面看不出什么来，如果有更完整的日志欢迎前往 #34 提交
