### ISSUE TITLE
显示注册推送成功。但是挂了两天没有收到任何消息。

### ISSUE THREAD

**Issue by heartacker** [Trumeet/MiPushFramework#50]
没有优化，没有绿色，后台可以联网，开机设置启动了，后台锁定。
![92b00a1919e30439f3637302e3d118d5254c152e](https://user-images.githubusercontent.com/1876302/35950836-853fbbd0-0cb3-11e8-86e6-0ddcb498aa62.jpg)
![828abbdd8cbdd2737b267f0773acdc77d284747c](https://user-images.githubusercontent.com/1876302/35950845-8e9ac59e-0cb3-11e8-962e-6f4b4fd0c820.jpg)

**Comment by Trumeet** [comment]
网易云 那里 没有 发（
