### ISSUE TITLE
弹不出通知和通知点击无效

### ISSUE THREAD

**Issue by TimothyZhang023** [Trumeet/MiPushFramework#51]
1. 弹不出通知
原因比较多，其中一个比较多的问题就是 #13  中我说的。extraNotification 是没有的
即使这个可以跳过，同样又可能有其他部分异常没有抛出导致notification 出不来，
我觉得我们可以手动构建 notification 

2. 通知点击无效
SDK中的getClickedPendingIntent 其实需要唤醒app，点击事件是一个startService (所以很多人只有打开应用才能跳转)
这个比较麻烦毕竟notification只有一个pendingintent，我在SDK > 24做了 3个Action ，可以打开 跳转，就是比较麻烦，但是看上去感觉应该可以工作。

**Comment by Trumeet** [comment]
感谢，欢迎 Pr~~pr~~

**Comment by TimothyZhang023** [comment]
PR #53  
简单弹窗 ，目前基本信息 和 intent 都是有的
large icon是应用图标以表示区分
mipush sdk中的intent基本都是交给应用处理，只有打开应用之后才能跳转 (但是我们这里只能设置一个Intent,我觉得这个可以优化)

SDK > 24会有两个按钮在下面 第一个是 开启应用第二个是 跳转 (contentIntent也是跳转)
效果你在coolapk上应该看过我发的图片。

**Comment by TimothyZhang023** [comment]
点击通知需要先拉起app然后startService，启动activity之后可能需要 Accessibility
可以考虑一下 这个[commit ](https://github.com/TimothyZhang023/MiPushFramework/commit/3e1ef15eb3a3edadbcbc97a2fc0cee1ac9130cc8)

**Comment by Trumeet** [comment]
嗯，非常感谢。但我有些疑问和建议，希望您在 Pr 中继续讨论，多谢。
建议比如说：
* 用 “使用情况 API” 代替辅助服务
* 不要加上那几个通知按钮（如酷安图上面），主要是我比较想做到和 MIUI 一模一样（
