### ISSUE TITLE
对于接收推送消息的应用要如何处理

### ISSUE THREAD

**Issue by yEs1do** [Trumeet/MiPushFramework#52]
我使用了补丁版黑域及绿色守护（绿色守护的处方允许小米推送）。

`Xiaomi Push Service Core` 未进行电池优化，黑域和绿色守护均未对其进行处理。但是接受推送的软件（如知乎）被黑域及绿色守护处理了，现在无法收到推送（无推送详情、无通知）。

反复尝试多种后台处理方案均无效，我接下来应该怎么做？

**Comment by Trumeet** [comment]
不黑域那些应用试试看？

**Comment by TimothyZhang023** [comment]
@Trumeet  miui会发广播通知app，特别是穿透类得，不黑域就会唤醒，增加耗电了吧

**Comment by TimothyZhang023** [comment]
知乎如果走mipush是可以收到详情的，这个我本地看到过，但是好像只是推荐信息，如果一段时间不开知乎就没了。。

**Comment by Trumeet** [comment]
@TimothyZhang023 确实，通知和穿透都要唤醒，但是通知应该显示了才会发广播的呀..（
不知道有什么影响

**Comment by TimothyZhang023** [comment]
广播有两种，一种是收到推送时候会尝试发送，比如注册结果通知app类。
还有就是打开通知栏的时候，但是如果app不在前台 oreo上logcat中看是被拦截了，应用收不到，也没法跳转，我不是太清楚miui上怎么处理，sdk中好像没有相关代码。
