### ISSUE TITLE
没有收到过推送

### ISSUE THREAD

**Issue by shuohao** [Trumeet/MiPushFramework#55]
网易新闻 网易云音乐 挖财 小米路由器 这几个APP注册成功 但是好几天都没收到过一次推送

**Comment by Trumeet** [comment]
事件里面没有吗？

**Comment by Trumeet** [comment]
事件里面没有吗？

**Comment by wangzhao2222** [comment]
是的。我是红米1s，安装了以后，服务正常。我用别人的微博给我的微博发私信，当微博还在后台的时候可以收到消息，mipush没收到。把微博丢到绿色守护后，mipush自然没收到消息

**Comment by TimothyZhang023** [comment]
@wangzhao2222  还在后台的时候可以收到消息，mipush没收到说明可能没有走mipush
微博标准版本的用户relate 的信息是走mipush的，只有垃圾信息才走。
推荐微博极速版好像可以。所以这个是微博问题。

**Comment by TimothyZhang023** [comment]
网易云音乐 最新版本打开推送可以收到穿透消息
小米路由器 这个确实收不到不清楚是不是应用关系，广告可以收到

`I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 01 70 5F 04 DF 88 CE DE CA D6 2A 39 C8 3B 94 8F E7 EA EF 94 84 FF 2E F7 8A 71 FA A5 A0 A8 D2 62 01 BC 91 4F 30 21 B1 09 82 06 0A 1C 44 26 AD DD B5 CE A8 16 01 B1 10 BC DD 38 DD 25 B0 6B 7A 98 16 A8 C3 3C A3 36 59 35 7E F9 84 2C 31 3E ED 69 5F 4D F3 60 8F 80 6A E8 76 1A A6 A6 8C 33 B3 EC CB 21 A7 8F DC F3 E0 CD 4C 15 6D 3C..., appid:1007575, packageName:com.xiaomi.router, target:Target(channelId:5, userId:58085545723, server:xiaomi.com, resource:anXAtTGE), metaInfo:PushMetaInfo(id:sdm03227518492259706MI, messageTs:1518492259706, title:小米WIFI, description:[新品]即热式电暖器，无感静音，守护整晚温暖, notifyType:1, passThrough:0, notifyId:700, extra:{}, internal:{score_info={"server_score":1,"group_interval":7200000,"extra_info":"[{\"v\":0,\"b\":-2.3593262647197135,\"w\":[2.001694519019869,0.315759268384101,0,0,2.6993593675271077],\"el\":[[30,1.1514274586209508],[0,0]],\"cl\":[[0,0]],\"cg\":[[0,0]],\"pkg\":{\"com.tencent.mm\":9,\"com.tencent.mobileqq\":9,\"com.android.mms\":9,\"com.android.calendar\":9,\"com.whatsapp\":9,\"com.facebook.orca\":9,\"com.google.android.gm\":9,\"com.google.androidE/PushCore: 
`

**Comment by wangzhao2222** [comment]
oh…可是我的网易云，知乎，B站都没有通过mipush收到消息…

**Comment by chphzz** [comment]
[file.log](https://github.com/Trumeet/MiPushFramework/files/1862689/file.log)
安装后过了24小时了，一条推送也没有收到。网易新闻这类APP，不会一天都没推送吧？
系统： 7.0
手机型号： 三星 C5010 ( C5 pro ）

**Comment by TimothyZhang023** [comment]
只有regist没有发送注册结果的可以卸载应用app重装
