### ISSUE TITLE
应用消息与push的推送消息重复

### ISSUE THREAD

**Issue by UiharuNeko** [Trumeet/MiPushFramework#57]
一加3，Oxygen OS公测31（Android8.0），最新版的push，收到消息时应用消息与push推送的消息重复

**Comment by TimothyZhang023** [comment]
可能因为
1. 程序在后台，并且没有切断广播。。。。so，这个我觉得可以优化。
2. 你手动点击通知，应用同样会重复处理一次，一些穿透类的会这样，比如酷安。这个需要容忍。

看你的描述应该是1。 这个问题是存在的。建议杀掉后台，禁止广播，省电美滋滋 :）

**Comment by UiharuNeko** [comment]
看log里程序一直在注册push，如果杀掉后台了会影响推送吗

**Comment by UiharuNeko** [comment]
看起来没啥问题了，非常感谢
