### ISSUE TITLE
通知重复且不会合并

### ISSUE THREAD

**Issue by Creedowl** [Trumeet/MiPushFramework#58]
应用已黑域，开了允许同步，现在应用本身会推送，mipush也会推送。。。 
![1](http://7xr5ep.com1.z0.glb.clouddn.com/Screenshot_20180214-090134.png) 
![2](http://7xr5ep.com1.z0.glb.clouddn.com/Screenshot_20180214-085909.png)
而且mipush的通知不会合并。。

**Comment by TimothyZhang023** [comment]
最新的snapshot么？

**Comment by Chen-Hu** [comment]
如果把应用的推送屏蔽掉的话？是会只通过mipush推送还是造成根本不推送了呢？

**Comment by TimothyZhang023** [comment]
通知会唤醒app， 切断唤醒即可
