### ISSUE TITLE
锤子到关闭省电的那一步点下一步就跳回上一页。

### ISSUE THREAD

**Issue by MundaneDefoliation** [Trumeet/MiPushFramework#6]
锤子到关闭省电的那一步点下一步就跳回上一页。

**Comment by Trumeet** [comment]
没有弹出关闭省电对话框？

**Comment by MundaneDefoliation** [comment]
锤子把关闭省电

**Comment by MundaneDefoliation** [comment]
锤子把关闭省电的这个给阉割了，所以就成无限循环了，希望每一页加个跳过的按钮。

**Comment by MundaneDefoliation** [comment]
@Trumeet 锤子把关闭省电的这个给阉割了，所以就成无限循环了，希望每一页加个跳过的按钮。

**Comment by Trumeet** [comment]
不是不是..
很不理解，这个页面除了手动点击后退是没有其他上一页逻辑的，怎么会回退

**Comment by MundaneDefoliation** [comment]
@Trumeet 就是这一页点了之后，因为系统没有这个功能，就自动退回上一页，就没法继续了，成无限循环了。

**Comment by shuohao** [comment]
确实是，在我锤手机中不能用，无法下一步

**Comment by Chen-Hu** [comment]
相同问题
Android 版本 6.0.1

**Comment by JamesZhutheThird** [comment]
有什么办法可以解决吗？

**Comment by Trumeet** [comment]
已修复： [Commit](https://github.com/Trumeet/MiPushFramework/commit/9150db6e769b464b9aef581e0a533d43fc3b6568)
将会使用一个单独的按钮进行请求，如果您的 ROM 不支持该功能您可以直接跳过。

下个版本中会生效，敬请关注。

**Comment by shuohao** [comment]
坐等下一版release
