### ISSUE TITLE
一加5t 8.0伪装miui后app没有提示注册

### ISSUE THREAD

**Issue by coverdh** [Trumeet/MiPushFramework#61]
最新快照版本

**Comment by TimothyZhang023** [comment]
什么app， 检查一下APP的XMPushService 是不是已经被禁用了

**Comment by Gontid** [comment]
同样的问题。一加3T，8.0最新open beta，所有后台管理已关闭，已装Magisk模块并向build.prop中加入更多MIUI键值。任何app都不会提示注册。

以酷安为例，在MyAndroidTools中确认XMPushService是打开状态，打开酷安后再回MAT，发现XMPushService已经变成关闭状态，而在小米推送服务中仍未提示注册。在MAT中打开XMPushService，打开酷安，XMPushService又变成关闭状态，如此循环往复。

卸载酷安重新安装仍然是相同的结果。其他app（如网易云），不会自动禁用XMPushService，但也不会注册。

**Comment by TimothyZhang023** [comment]
灵异事件无法解释。

**Comment by TimothyZhang023** [comment]
开启伪装之后 重置应用两种方案
1. 重新开启XMPushService并清空应用数据
2. 卸载并重新安装
