### ISSUE TITLE
收到通知不推

### ISSUE THREAD

**Issue by PixelGe** [Trumeet/MiPushFramework#65]
Developer Info:
XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 02 D0 82 E8 35 39 EF FB 41 BA F2 3A 3C E8 A1 AD 2D 1A FF 6D EC 42 A9 9C 6E 8A CE A6 AF C0 AF 5D 7E ED F2 80 03 F9 02 1B E3 0B 27 75 A9 26 E2 AA 9C AD 90 D5 A1 14 D0 8A F9 66 B5 1E D1 8E A0 6C EE 4A FE 4A 49 EB 05 66 40 AB 8F 71 2B 2F AB 1B BF 66 00 10 3D 58 37 BC 12 04 C4 CF 25 93 EB 89 E9 59 45 D3 42 2D E2 0F 99 64 E1 F8..., appid:2882303761517509924, packageName:com.ss.android.ugc.aweme, target:Target(channelId:5, userId:58152452651, server:xiaomi.com, resource:anegDLJb), metaInfo:PushMetaInfo(id:adm04191519094619613VE.66738618, messageTs:1519094619613, description:@✨宸荨樱桃: sexy jazz🌚舞就这么跳，别说我变了…, notifyType:0, passThrough:1, notifyId:0, extra:{callback=http://it.snssdk.com/cloudpush/callback/mipush/?appid=1128&rid=66738618, callback.type=1, jobkey=66738618}, ignoreRegInfo:false))

**Comment by TimothyZhang023** [comment]
有内容没有标题

fixed at 19dd9e1c614fcdcf058c1a7c75e84554b1922d59
