### ISSUE TITLE
不即时推送，只有在网络状态改变时才推送

### ISSUE THREAD

**Issue by w1324296014** [Trumeet/MiPushFramework#68]
比如说刚刚连接通VPN时会突然推送一大堆，或者刚开启wifi时也会推送一大堆，平时不声不响的-_-  root了，只装了黑域一款防止流氓的app，还没有黑域它(com.xiaomi.xmsf)，电池也没有优化，安卓7.1 lineage os.

issue2:IT之家，酷安，知乎没有收到推送，也没有出现允许的提示，安装了Magisk的fake模块也启用了。

建议：加入一个取消常驻通知栏的选项~如果这样会让系统自动杀掉后台的话就当我没说~

**Comment by w1324296** [comment]
酷安大佬，求fix方案～

**Comment by w1324296** [comment]
注意到push的APP权限里没有“防止手机休眠”  这一权限，不知道如果加上这一权限并允许，会不会能解决呢？

**Comment by Janet-Baker** [comment]
千万别阻止手机休眠，我会忍不住用appops封杀的( p′︵‵。)

**Comment by TimothyZhang023** [comment]
最新版已经fix， 如有需要请reopen
