### ISSUE TITLE
目前最新版本2018.2.20，点击通知栏的通知会显示“Push已停止运行” 

### ISSUE THREAD

**Issue by w1324296014** [Trumeet/MiPushFramework#69]
安卓7.1，Lineage os，装了黑域，Magisk，模块只有mipush fake，电池也未优化。今天更新到最新的版本，点击通知栏一个即刻的新闻，就出现了“Push已停止运行” ，再点就”Push屡次停止运行“，但常驻通知栏的"Mi Push  running"还在。
以下是相关log，那个新闻”菲律宾愿成为中国一个省“ 是点击这个新闻之后停止运行的。

I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 01 F0 88 DE 61 C9 DE 3C 44 77 04 07 89 A6 92 7D 95 58 7C 69 B2 C2 DD 12 B5 C4 9E D4 03 EC 9A 45 80 4C F8 EC 82 32 C2 AF 9D FE 60 DA 7F 04 94 75 83 C6 9E 31 41 0C 18 EB DB 3D AC 25 15 AD 19 46 93 19 3E 26 AC 73 01 2E 0F 26 6A 32 92 C3 F3 17 28 4D 0C D3 64 D3 3C 6A FA 7D 47 4E 57 3F FE 07 CF 46 1E 40 1B 1C 29 73 7F B0 0F 37..., appid:2882303761517557334, packageName:com.swjtu.gcmformojo, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:an9ZgBQH), metaInfo:PushMetaInfo(id:scm54904519118513699G0, messageTs:1519118513699, notifyType:0, passThrough:1, notifyId:0, extra:{}, ignoreRegInfo:false))
I/MyMIPushMessageProcessor: receive a message, appid=2882303761517557334, msgid= scm54904519118513699G0
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 01 D0 88 DE 61 C9 DE 3C 44 77 04 07 89 A6 92 7D 95 58 7C 69 B2 C2 DD 12 B5 C4 9E D4 03 EC 9A 45 80 4C F8 EC 82 32 C2 AF 9D FE 60 DA 7F 04 94 75 83 C6 9E 31 41 0C 18 EB DB 3D AC 25 15 AD 19 46 93 19 3E 26 AC 73 01 2E 0F 26 6A 32 92 C3 F3 17 28 4D 6C B4 FB BF E5 BE 85 88 DC 93 C2 11 1F 81 BA 51 39 3D 0D 04 01 B2 60 CD 47 E5..., appid:2882303761517557334, packageName:com.swjtu.gcmformojo, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:an9ZgBQH), metaInfo:PushMetaInfo(id:scm53106519119207603A6, messageTs:1519119207603, notifyType:0, passThrough:1, notifyId:0, extra:{}, ignoreRegInfo:false))
I/MyMIPushMessageProcessor: receive a message, appid=2882303761517557334, msgid= scm53106519119207603A6
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 01 90 71 A0 D4 38 89 1A 35 A6 77 B1 43 47 EA 04 84 CA E6 79 FC D0 73 5A 7A FA 04 FE C9 F2 21 73 C2 F8 DB 7C 82 B1 5D D3 EC 27 33 79 A7 A1 AB F0 97 3D 30 F7 D0 72 DA B8 46 2B 64 68 62 B3 AC 94 EF 56 71 C7 DE 3F 16 1B E4 26 A2 9C 25 7E 96 29 D9 19 81 DC FE B7 6E 3C 07 98 60 0C 7A 82 3C D5 49 0C CA 8D 0A DD F2 30 CF 59 BA 1F..., appid:2882303761517330029, packageName:com.ruguoapp.jike, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:an9ZgBQH), metaInfo:PushMetaInfo(id:sdm01721519120632058xt, messageTs:1519120632058, title:每日国际视野, description:【杜特尔特：菲律宾愿成为中国一个省】19日，杜特尔特出席了在马尼拉举行的中菲企业家会议。当有媒体问及若中国在南海建设“军事基地”，菲律宾是否会担心时，杜特尔特表示，完全不担心，因为那只可能是为防御美国。他还提议，“如果中国愿意，你们可以把菲律宾变成中国的一个省份，像福建一样”。, notifyType:4, passThrough:0, notifyId:849692878, extra:{}, internal:{score_info={"server_score":1,"group_interval":7200000,"extra_info":"[{\"v\":0,\"b\":-2.3593262647197135,\"w\":[2.001694519019869,0.315759268384101,0,0,2.6993593675271077],\"el\":[[30,1.1514274586209508],[0,0]],\"cl\":[[0,0]],\"cg\":[[0,0]],\"pkg\":{\"com.tencent.mm\":9,\"com.tencent.mobileqq\":9,\"com.android.mms\":9,\"com.android.calendar\":9,\"com.whatsapp\":9,\"com.facebook.orca\":9,\"com.google.android.gm\":9,\"com.google.android.calendar\":9,\"com.android.deskclock\":9,\"com.android.phone\":9,\"com.android.stk\":9,\"com.android.cellbroadcastreceiver\":9,\"com.android.incallui\":9,\"com.android.server.telecom\":9,\"com.android.email\":9,\"com.xiaomi.channel\":9,\"com.android.updater\":9,\"com.android.settings\":9,\"com.miui.player\":9,\"com.miui.bugreport\":9,\"com.eg.android.AlipayGphone\":9,\"com.xiaomi.market\":9,\"com.android.providers.downloads\":9,\"com.alibaba.android.rimet.alidingtalk\":9,\"com.alibaba.android.rimet\":9},\"th\":0.5,\"n\":3}]","threshold":0.67,"sort_delay":10000,"server_strategy":"20170517_1906_2"}}, ignoreRegInfo:false))
I/MyMIPushMessageProcessor: receive a message, appid=2882303761517330029, msgid= sdm01721519120632058xt
I/MyMIPushNotificationHelper: title:每日国际视野  description:【杜特尔特：菲律宾愿成为中国一个省】19日，杜特尔特出席了在马尼拉举行的中菲企业家会议。当有媒体问及若中国在南海建设“军事基地”，菲律宾是否会担心时，杜特尔特表示，完全不担心，因为那只可能是为防御美国。他还提议，“如果中国愿意，你们可以把菲律宾变成中国的一个省份，像福建一样”。
W/XMPushService Bridge: Don't register multi request com.swjtu.gcmformojo
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 03 90 88 DE 61 C9 DE 3C 44 77 04 07 89 A6 92 7D 95 58 7C 69 B2 C2 DD 12 B5 C4 9E D4 03 EC 9A 45 80 4C F8 EC 82 32 C2 AF 9D FE 60 DA 7F 04 94 75 83 C6 9E 31 41 0C 18 EB DB 3D AC 25 15 AD 19 46 93 19 3E 26 AC 73 01 2E 0F 26 6A 32 92 C3 F3 17 28 4D D2 43 58 90 F1 D1 E9 63 6B 0D 64 4E DB 77 9C 67 58 0D A1 FC 61 26 DF AD 77 71..., appid:2882303761517557334, packageName:com.swjtu.gcmformojo, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:an9ZgBQH), metaInfo:PushMetaInfo(id:scm50720519121507348im, messageTs:1519121507348, notifyType:0, passThrough:1, notifyId:0, extra:{}, ignoreRegInfo:false))
I/MyMIPushMessageProcessor: receive a message, appid=2882303761517557334, msgid= scm50720519121507348im
W/XMPushService Bridge: Don't register multi request com.swjtu.gcmformojo

**Comment by wuchjun** [comment]
同样问题

**Comment by TimothyZhang023** [comment]
有crash的log么？

**Comment by TimothyZhang023** [comment]
#64

**Comment by TimothyZhang023** [comment]
最新版增加了兼容模式
