### ISSUE TITLE
新版修改build的时候失败

### ISSUE THREAD

**Issue by 1176020631** [Trumeet/MiPushFramework#7]
机型：oneplus 3t 不知道是不是个例，先提交issue吧

**Comment by Trumeet** [comment]
看评论是挂载问题。
请抓取日志（Tag：Shell）完整的给我。

**Comment by 1176020631** [comment]
怎么抓啊....

**Comment by 1176020631** [comment]
@Trumeet 抓取要什么软件

**Comment by Trumeet** [comment]
matlog，手机上的

**Comment by 1176020631** [comment]
软件输入shell只有这么点`08-26 10:52:03.036 I/dboxed_process1(31684): type=1400 audit(0.0:20832): avc: denied { search } for name="tmp" dev="dm-0" ino=236887 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=1`

**Comment by cubesky** [comment]
08-27 20:30:57.187 28024-28169/com.xiaomi.xmsf D/Shell: Exec:mount -o rw,remount,rw /system
08-27 20:30:57.671 28024-28193/com.xiaomi.xmsf D/AppTracker: App Event: stop
08-27 20:30:59.304 28024-28169/com.xiaomi.xmsf D/Shell: SuccessMsg:
08-27 20:30:59.304 28024-28169/com.xiaomi.xmsf D/Shell: ErrMsg:mount: '/dev/block/dm-0'->'/system': Device or resource busy
08-27 20:30:59.305 28024-28169/com.xiaomi.xmsf D/Shell: Exec:sed -i '$a # Fake MIUI build by XiaomiPushServiceFramework.' /system/build.prop
08-27 20:30:59.362 28024-28233/com.xiaomi.xmsf D/AppTracker: App Event: start
08-27 20:30:59.381 28024-28169/com.xiaomi.xmsf D/Shell: SuccessMsg:
08-27 20:30:59.381 28024-28169/com.xiaomi.xmsf D/Shell: ErrMsg:sed: no temp file
08-27 20:30:59.395 28024-28169/com.xiaomi.xmsf D/Shell: Exec:sed -i '$a ro.miui.ui.version.name=HELLO' /system/build.prop
08-27 20:30:59.455 28024-28169/com.xiaomi.xmsf D/Shell: SuccessMsg:
08-27 20:30:59.455 28024-28169/com.xiaomi.xmsf D/Shell: ErrMsg:sed: no temp file
08-27 20:30:59.455 28024-28169/com.xiaomi.xmsf D/Shell: Exec:chmod 644 /system/build.prop
08-27 20:30:59.520 28024-28169/com.xiaomi.xmsf D/Shell: SuccessMsg:
08-27 20:30:59.520 28024-28169/com.xiaomi.xmsf D/Shell: ErrMsg:chmod: chmod '/system/build.prop' to 100644: Read-only file system
08-27 20:30:59.520 28024-28169/com.xiaomi.xmsf D/Shell: Exec:mount -o ro,remount,ro /system
08-27 20:30:59.601 28024-28169/com.xiaomi.xmsf D/Shell: SuccessMsg:
08-27 20:30:59.601 28024-28169/com.xiaomi.xmsf D/Shell: ErrMsg:mount: '/dev/block/dm-0'->'/system': Device or resource busy

**Comment by cubesky** [comment]
I found a solution on Magisk.
Run these command.

```shell
su
resetprop ro.miui.ui.version.name HELLO
```

It will change `build.prop` with `Magisk resetprop applets`

**Comment by cubesky** [comment]
I make a Magisk Module for this. 
https://github.com/cubesky/MiPushFake

**Comment by Trumeet** [comment]
@cubesky 感谢立音姐姐~

**Comment by 1176020631** [comment]
@cubesky Are you a little foreign sister?

**Comment by cubesky** [comment]
@1176020631 别在意 (ーー;)

**Comment by 1176020631** [comment]
@cubesky 2333

**Comment by Trumeet** [comment]
下个版本会改用立音姐姐的 [Magisk模块](https://github.com/cubesky/MiPushFake) 进行伪装，**弃用Root修改**。 
@1176020631 @cubesky
