### ISSUE TITLE
知乎不会注册推送&只在开启任意一个已注册的应用后才一次性推送

### ISSUE THREAD

**Issue by Rongronggg9** [Trumeet/MiPushFramework#72]
知乎不注册推送，列表里亦不出现知乎。
查看组件可发现MiPush相关组件被默认禁用。尝试手动开启，仍旧不注册，再次查看发现MiPush组件又被禁用。
尝试清除知乎应用数据，问题依旧。
已伪装MIUI，排除所有对Push的省电。
Play最新版知乎。

其他应用可成功注册并推送，惟如其他反馈所言常常不及时推送并一次性推送未推送的信息。推送时机常常为开启一个已注册的应用。检查发现Push服务常常自动结束，尝试安装为系统应用问题依旧。
不知为何获取日志为空…

最新Snapshot版。

**Comment by TimothyZhang023** [comment]
> 
只在开启任意一个已注册的应用后才一次性推送问题 


 这个尝试最新snapshot

**Comment by TimothyZhang023** [comment]
zhihu需要
ro.miui.internal.storage

**Comment by TimothyZhang023** [comment]
closed due to inactive
