### ISSUE TITLE
在华为nova上(emui5.0)工作时设备发热加重

### ISSUE THREAD

**Issue by zzsvt** [Trumeet/MiPushFramework#8]
0.2/0.3版在华为nova上(emui5.0-安卓7.0版本)工作时设备发热略有加重
记录 应用 设定 都显示空白但是消息推送正常
0.1版则好像没这些问题

**Comment by Trumeet** [comment]
应该跟这个无关吧.. 看一下推送服务的耗电量？

**Comment by zzsvt** [comment]
厄日志http://pan.stnts.com/s/cQ9iPji

**Comment by benzBrake** [comment]
你是怎么开启推送的，我是V9 emui5.1 安卓7.0，没有能开启推送的

**Comment by zzsvt** [comment]
看看这个(ฅ∀<`๑)╭
https://www.coolapk.com/feed/4081150


在2017年9月6日 下午7:57:12 Ryan Lieu <notifications@github.com>写道：

**Comment by crazyvest** [comment]
华为自己就有推送为啥还要米push？有米push的app一般都有华为push

**Comment by TimothyZhang023** [comment]
不太觉得push会导致发热。如果有，一定是emui的问题。

close due to inactive
