### ISSUE TITLE
锤子手机M1L 可以使用。但是推送时只出现在记录里，不会触发系统推送。

### ISSUE THREAD

**Issue by Chen-Hu** [Trumeet/MiPushFramework#86]
锤子手机M1L，可以安装使用。
在【小米推送服务】的记录中会有记录，但是不触发系统推送。
如图
![screenshot_2018-03-19-09-29-51-590_](https://user-images.githubusercontent.com/6964498/37695449-4799ed24-2d0a-11e8-8638-49f54b951e96.png)

**Comment by Chen-Hu** [comment]
更新，应用【转转】可以支持推送。

**Comment by shuohao** [comment]
我的是锤子坚果Pro 也是这样 都不会推送 只是有记录

**Comment by TimothyZhang023** [comment]
麻烦提供一下push的日志吧。手边没有锤子手机，看上去所有锤子rom都有问题

**Comment by Trumeet** [comment]
@TimothyZhang023 为什么 Repoen 了？

**Comment by TimothyZhang023** [comment]
> @TimothyZhang023 为什么 Repoen 了？

我也忘了。 是不是引用时候自动reopen的？
