### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mikuxs** [Trumeet/MiPushFramework#87]
软件服务正常，模块也装了，软件的权限全给了，后台有留着，软件来有推送记录，但我没看到推送

**Comment by Chen-Hu** [comment]
我也遇到相同问题。
但是 app 【转转】  一切正常。。

**Comment by xydche** [comment]
同样的问题，有推送记录，就是没有通知，所有的省电后台都设置好了

**Comment by TimothyZhang023** [comment]
推送记录又标题和内容么

**Comment by TimothyZhang023** [comment]
close due to inactive
