### ISSUE TITLE
在锤子系列手机上都没法用

### ISSUE THREAD

**Issue by shuohao** [Trumeet/MiPushFramework#94]
大部分无法推送，有的推送也只是在应用的推送记录里而不是系统的通知栏推送

**Comment by TimothyZhang023** [comment]
麻烦提供一下push的日志，thks

**Comment by shuohao** [comment]
Developer Info:
XmPushActionContainer(action:SendMessage, encryptAction:true, isRequest:false, pushAction:08 00 01 00 00 00 05 02 00 02 01 02 00 03 00 0B 00 04 00 00 01 10 84 0F E3 0D AF 21 B7 F1 7D C9 C9 BA 24 9C 9D A3 5B 81 45 06 7A 59 93 7E 5A 52 98 4F 59 00 3D F0 22 58 F4 EB 00 ED 6D 84 D7 1A 84 72 86 FA 50 D9 CF 11 01 7A 8C 4B BF FD F9 8F 2C E2 AE 0A EC 14 C5 55 22 49 10 71 B4 26 68 5F 58 1B EF 2E FA 53 78 49 54 24 1D 13 3C B5 0A 8A 57 C5 AA 0B F2 22 11 CA EC A2 10 1C 95 01 36 26..., appid:2882303761517144595, packageName:cmb.pb, target:Target(channelId:5, userId:57878398109, server:xiaomi.com, resource:anPOSKUy), metaInfo:PushMetaInfo(id:scm50273523968546516Nd, messageTs:1523968546516, title:招商银行, description:您尾号8337的招行账户支出人民币100.00元, notifyType:1, passThrough:0, notifyId:102, extra:{message_count=0, UserId=600000000102, PT=1523968546500, ToUserId=409330199, ZHCH=1001, intent_uri=intent:#Intent;component=cmb.pb/com.mb.zhaohusdk.ui.activitys2.SessionListAct;end, MsgId=2018041720354646914847584, URL=, notify_effect=2}, internal:{score_info={"server_score":1,"group_interval":7200000,"extra_info":"[{\"v\":0,\"b\":-0.9286723974419155,\"w\":[14.042300660848042,-0.10482109151915309,0,0,0],\"el\":[[30,0],[0,0]],\"cl\":[[0,0]],\"cg\":[[0,0]],\"pkg\":{\"com.tencent.mm\":9,\"com.tencent.mobileqq\":9,\"com.android.mms\":9,\"com.android.calendar\":9,\"com.whatsapp\":9,\"com.facebook.orca\":9,\"com.google.android.gm\":9,\"com.google.android.calendar\":9,\"com.android.deskclock\":9,\"com.android.phone\":9,\"com.android.stk\":9,\"com.android.cellbroadcastreceiver\":9,\"com.android.incallui\":9,\"com.android.server.telecom\":9,\"com.android.email\":9,\"com.xiaomi.channel\":9,\"com.android.updater\":9,\"com.android.settings\":9,\"com.miui.player\":9,\"com.miui.bugreport\":9,\"com.eg.android.AlipayGphone\":9,\"com.xiaomi.market\":9,\"com.android.providers.downloads\":9,\"com.alibaba.android.rimet.alidingtalk\":9,\"com.alibaba.android.rimet\":9},\"th\":0.5,\"n\":3}]","threshold":0.67,"sort_delay":10000,"server_strategy":"template"}}, ignoreRegInfo:false))

**Comment by TimothyZhang023** [comment]
设定-> 获取日志

**Comment by shuohao** [comment]
[file.log](https://github.com/Trumeet/MiPushFramework/files/1922404/file.log)
