### ISSUE TITLE
功能建议:增加新注册应用默认为“自动，允许注册”的选项

### ISSUE THREAD

**Issue by techxiu** [Trumeet/MiPushFramework#95]
因为一般弹出那个框我都是点允许的，刚刚支付宝弹出时候卡了一下，导致我没有按到允许就消失了，进入“小米推送服务”显示是拒绝的，手动改自动允许注册了，希望有设置默认的选项_(:з」∠)_

**Comment by stustu29** [comment]
相比这个，可能还是增加个设置选项让用户自行设置较好吧(:з っ )っ

**Comment by TimothyZhang023** [comment]
我觉得可以做一个全局自动允许

**Comment by TimothyZhang023** [comment]
done at 188ed05af6161a6640d71220cba53c2d0b029afa
