### ISSUE TITLE
关于同时收到两个推送的问题

### ISSUE THREAD

**Issue by 95e2** [Trumeet/MiPushFramework#96]
我现在有一个软件大概是知乎新闻类的软件，每次收到推送都有两条，点击MiPushFramework的那条推送会崩溃。

**Comment by 95e2** [comment]
好像只是单纯得存在MiPushManager和MiPushFramework同时推送的问题，之前没仔细看。另外希望加入删除注册的功能而不是阻止注册，删掉的软件记录看着不是很舒服。。。

**Comment by TimothyZhang023** [comment]
切断应用唤醒可以解决

**Comment by TimothyZhang023** [comment]
新版可以关闭对应用唤醒，避免重复通知
