### ISSUE TITLE
[feature request] 在一些 ROM 上利用提权漏洞给 Push Service 提权

### ISSUE THREAD

**Issue by Trumeet** [Trumeet/MiPushFramework#97]
在一些官改、第三方 ROM 上，ROMer 会以 Google 提供的测试签名给 platform 签名。我们可以利用该签名达到 system uid 的效果。

TODO 
 - [x] 对 Push 增加 system flavor，在该 flavor 的 manifest 中设置 shared uid 以及在 gradle 中设置签名
 - [x] 更改 Push 提供的权限 protection level，以便使非 platform 签名的 manager 得以使用
 - [x] 在下载 service 的提示方面加入判断
 - [x] 在 manager 主界面提醒用户可以使用 system 版本 service
 - [x] 使用 platform 权限执行一些操作，比如常驻

**Comment by heruoxin** [comment]
作大死，建议对该种渠道包单独用一个包名，以免被封杀（

**Comment by keith-xiong** [comment]
通知栏就不用常驻通知了吗🤔

**Comment by Trumeet** [comment]
@heruoxin 没办法的.. App 只会识别特定包名（
