### ISSUE TITLE
努比亚UI无法收到通知，点击修复失败

### ISSUE THREAD

**Issue by spendks** [Trumeet/MiPushFramework#98]
将小米推送服务设置为系统应用后也不行，列表有应用支持但无法接受通知，点击修复失败。
机型:努比亚z17mini，安卓6.0，努比亚UI5.0

**Comment by ecustwx** [comment]
这个检查应用支持的软件是什么

**Comment by TimothyZhang023** [comment]
这个功能由于bug过多已经移除。
你可以手动使用写轮眼启用XMPushService
